In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/home/koushik/modelling.csv", parse_dates=['VALUATION'])

/home/koushik/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data

,Unnamed: 0,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
0,0,10001,2015-01-31,ACTIVE,8299.0,01-01-2012,1900,36.993840,36,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,0,12
1,1,10001,2015-02-28,ACTIVE,8299.0,01-01-2012,1900,37.913758,37,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,1,12
2,2,10001,2015-03-31,ACTIVE,8299.0,01-01-2012,1900,38.932238,38,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,2,12
3,3,10001,2015-04-30,ACTIVE,8299.0,01-01-2012,1900,39.917864,39,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
4,4,10001,2015-05-31,ACTIVE,8299.0,01-01-2012,1900,40.936345,40,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,4,12
5,5,10001,2015-06-30,ACTIVE,8299.0,01-01-2012,1900,41.921971,41,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,5,12
6,6,10001,2015-07-31,ACTIVE,8299.0,01-01-2012,1900,43.058339,42,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,6,12
7,7,10001,2015-08-31,ACTIVE,8299.0,01-01-2012,1900,43.958932,43,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,7,12
8,8,10001,2015-09-30,ACTIVE,8299.0,01-01-2012,1900,44.944559,44,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,8,12
9,9,10001,2015-10-31,ACTIVE,8299.0,01-01-2012,1900,45.963039,45,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,9,12
10,10,10001,2015-11-30,ACTIVE,8299.0,01-01-2012,1900,46.948665,46,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,10,12
11,11,10001,2015-12-31,ACTIVE,8299.0,01-01-2012,1900,47.967146,47,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,11,12
12,12,10001,2016-01-31,ACTIVE,8299.0,01-01-2012,1900,48.985626,48,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,12,12
13,13,10001,2016-02-29,ACTIVE,8299.0,01-01-2012,1900,49.938398,49,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,13,12
14,14,10001,2016-03-31,ACTIVE,8299.0,01-01-2012,1900,50.956879,50,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,14,12
15,15,10001,2016-04-30,ACTIVE,8299.0,01-01-2012,1900,51.942505,51,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,15,12
16,16,10001,2016-05-31,ACTIVE,8299.0,01-01-2012,1900,52.960986,52,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,16,12
17,17,10001,2016-06-30,Active,8299.0,01-01-2012,1900,52.961000,53,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,17,12
18,18,10001,2016-07-31,ACTIVE,8299.0,01-01-2012,1900,54.965092,54,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,18,12
19,19,10001,2016-08-31,ACTIVE,8299.0,01-01-2012,1900,55.983573,55,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,19,12
20,20,10001,2016-09-30,ACTIVE,8299.0,01-01-2012,1900,56.969199,56,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,20,12
21,21,10001,2016-10-31,ACTIVE,8299.0,01-01-2012,1900,57.987680,57,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,21,12
22,22,10001,2016-11-30,ACTIVE,8299.0,01-01-2012,1900,58.973306,58,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,22,12
23,23,10001,2016-12-31,ACTIVE,8299.0,01-01-2012,1900,59.991786,59,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,23,12
24,24,10001,2017-01-31,ACTIVE,8299.0,01-01-2012,1900,61.010267,60,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,24,12
25,25,10001,2017-02-28,ACTIVE,8299.0,01-01-2012,1900,61.930185,61,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,25,12
26,26,10003,2015-01-31,ACTIVE,5211.0,01-01-2012,200,36.993840,36,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,26,12
27,27,10003,2015-02-28,ACTIVE,5211.0,01-01-2012,200,37.913758,37,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,27,12
28,28,10003,2015-03-31,ACTIVE,5211.0,01-01-2012,200,38.932238,38,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,28,12
29,29,10003,2015-04-30,ACTIVE,5211.0,01-01-2012,200,39.917864,39,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,29,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182989,182989,A1,2016-06-30,Active,NaN,01-01-2010,3800,76.944600,77,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182989,12
182990,182990,A1,2016-07-31,ACTIVE,NaN,01-01-2010,3800,78.948665,78,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182990,12
182991,182991,A1,2016-08-31,ACTIVE,NaN,01-01-2010,3800,79.967146,79,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182991,12
182992,182992,A1,2016-09-30,ACTIVE,NaN,01-01-2010,3800,80.952772,80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182992,12
182993,182993,A1,2016-10-31,ACTIVE,NaN,01-01-2010,3800,81.971253,81,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182993,12
182994,182994,A1,2016-11-30,ACTIVE,NaN,01-01-2010,3800,82.956879,82,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182994,12
182995,182995,A1,2016-12-31,ACTIVE,NaN,01-01-2010,3800,83.975359,83,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182995,12
182996,182996,A1,2017-01-31,ACTIVE,NaN,01-01-2010,3800,84.993840,84,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182996,12
182997,182997,A1,2017-02-28,ACTIVE,NaN,01-01-2010,3800,85.913758,85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182997,0
182998,182998,A2,2015-01-31,ACTIVE,NaN,01-03-2010,200,59.039014,58,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182998,12
182999,182999,A2,2015-02-28,ACTIVE,NaN,01-03-2010,200,59.958932,59,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182999,12
183000,183000,A2,2015-03-31,ACTIVE,NaN,01-03-2010,200,60.977413,60,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183000,12
183001,183001,A2,2015-04-30,ACTIVE,NaN,01-03-2010,200,61.963039,61,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183001,12
183002,183002,A2,2015-05-31,ACTIVE,NaN,01-03-2010,200,62.981520,62,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183002,12
183003,183003,A2,2015-06-30,ACTIVE,NaN,01-03-2010,200,63.967146,63,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183003,12
183004,183004,A2,2015-07-31,ACTIVE,NaN,01-03-2010,200,65.164036,64,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183004,12
183005,183005,A2,2015-08-31,ACTIVE,NaN,01-03-2010,200,66.004107,65,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183005,12
183006,183006,A2,2015-09-30,ACTIVE,NaN,01-03-2010,200,66.989733,66,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183006,12
183007,183007,A2,2015-10-31,ACTIVE,NaN,01-03-2010,200,68.008214,67,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183007,12
183008,183008,A2,2015-11-30,ACTIVE,NaN,01-03-2010,200,68.993840,68,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183008,12
183009,183009,A2,2015-12-31,ACTIVE,NaN,01-03-2010,200,70.012320,69,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183009,12
183010,183010,A2,2016-01-31,ACTIVE,NaN,01-03-2010,200,71.030801,70,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183010,12
183011,183011,A2,2016-02-29,ACTIVE,NaN,01-03-2010,200,71.983573,71,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183011,12
183012,183012,A2,2016-03-31,ACTIVE,NaN,01-03-2010,200,73.002053,72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183012,12
183013,183013,A2,2016-04-30,ACTIVE,NaN,01-03-2010,200,73.987680,73,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183013,12
183014,183014,A2,2016-05-31,ACTIVE,NaN,01-03-2010,200,75.006160,74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183014,12
183015,183015,A2,2016-06-30,Active,NaN,01-03-2010,200,75.006200,75,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183015,3
183016,183016,A2,2016-07-31,ACTIVE,NaN,01-03-2010,200,77.010267,76,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183016,0
183017,183017,A2,2016-08-31,ACTIVE,NaN,01-03-2010,200,78.028747,77,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183017,0
183018,183018,A2,2016-09-30,LAPSED,NaN,01-03-2010,200,79.014374,78,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183018,0

In [12]:
for i in range(0,len(data)):
    if data.iloc[i,62] != 12:
        data.iloc[i,62] = 3

In [13]:
data

,Unnamed: 0,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
0,0,10001,2015-01-31,ACTIVE,8299.0,01-01-2012,1900,36.993840,36,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
1,1,10001,2015-02-28,ACTIVE,8299.0,01-01-2012,1900,37.913758,37,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
2,2,10001,2015-03-31,ACTIVE,8299.0,01-01-2012,1900,38.932238,38,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
3,3,10001,2015-04-30,ACTIVE,8299.0,01-01-2012,1900,39.917864,39,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
4,4,10001,2015-05-31,ACTIVE,8299.0,01-01-2012,1900,40.936345,40,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
5,5,10001,2015-06-30,ACTIVE,8299.0,01-01-2012,1900,41.921971,41,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
6,6,10001,2015-07-31,ACTIVE,8299.0,01-01-2012,1900,43.058339,42,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
7,7,10001,2015-08-31,ACTIVE,8299.0,01-01-2012,1900,43.958932,43,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
8,8,10001,2015-09-30,ACTIVE,8299.0,01-01-2012,1900,44.944559,44,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
9,9,10001,2015-10-31,ACTIVE,8299.0,01-01-2012,1900,45.963039,45,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
10,10,10001,2015-11-30,ACTIVE,8299.0,01-01-2012,1900,46.948665,46,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
11,11,10001,2015-12-31,ACTIVE,8299.0,01-01-2012,1900,47.967146,47,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
12,12,10001,2016-01-31,ACTIVE,8299.0,01-01-2012,1900,48.985626,48,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,12,12
13,13,10001,2016-02-29,ACTIVE,8299.0,01-01-2012,1900,49.938398,49,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
14,14,10001,2016-03-31,ACTIVE,8299.0,01-01-2012,1900,50.956879,50,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
15,15,10001,2016-04-30,ACTIVE,8299.0,01-01-2012,1900,51.942505,51,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
16,16,10001,2016-05-31,ACTIVE,8299.0,01-01-2012,1900,52.960986,52,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
17,17,10001,2016-06-30,Active,8299.0,01-01-2012,1900,52.961000,53,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
18,18,10001,2016-07-31,ACTIVE,8299.0,01-01-2012,1900,54.965092,54,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
19,19,10001,2016-08-31,ACTIVE,8299.0,01-01-2012,1900,55.983573,55,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
20,20,10001,2016-09-30,ACTIVE,8299.0,01-01-2012,1900,56.969199,56,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,12
21,21,10001,2016-10-31,ACTIVE,8299.0,01-01-2012,1900,57.987680,57,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,3,12
22,22,10001,2016-11-30,ACTIVE,8299.0,01-01-2012,1900,58.973306,58,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,3,12
23,23,10001,2016-12-31,ACTIVE,8299.0,01-01-2012,1900,59.991786,59,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,3,12
24,24,10001,2017-01-31,ACTIVE,8299.0,01-01-2012,1900,61.010267,60,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,3,12
25,25,10001,2017-02-28,ACTIVE,8299.0,01-01-2012,1900,61.930185,61,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,3,12
26,26,10003,2015-01-31,ACTIVE,5211.0,01-01-2012,200,36.993840,36,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,3,12
27,27,10003,2015-02-28,ACTIVE,5211.0,01-01-2012,200,37.913758,37,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,3,12
28,28,10003,2015-03-31,ACTIVE,5211.0,01-01-2012,200,38.932238,38,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,3,12
29,29,10003,2015-04-30,ACTIVE,5211.0,01-01-2012,200,39.917864,39,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,3,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182989,182989,A1,2016-06-30,Active,NaN,01-01-2010,3800,76.944600,77,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182990,182990,A1,2016-07-31,ACTIVE,NaN,01-01-2010,3800,78.948665,78,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182991,182991,A1,2016-08-31,ACTIVE,NaN,01-01-2010,3800,79.967146,79,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182992,182992,A1,2016-09-30,ACTIVE,NaN,01-01-2010,3800,80.952772,80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182993,182993,A1,2016-10-31,ACTIVE,NaN,01-01-2010,3800,81.971253,81,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182994,182994,A1,2016-11-30,ACTIVE,NaN,01-01-2010,3800,82.956879,82,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182995,182995,A1,2016-12-31,ACTIVE,NaN,01-01-2010,3800,83.975359,83,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182996,182996,A1,2017-01-31,ACTIVE,NaN,01-01-2010,3800,84.993840,84,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182997,182997,A1,2017-02-28,ACTIVE,NaN,01-01-2010,3800,85.913758,85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,3
182998,182998,A2,2015-01-31,ACTIVE,NaN,01-03-2010,200,59.039014,58,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
182999,182999,A2,2015-02-28,ACTIVE,NaN,01-03-2010,200,59.958932,59,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183000,183000,A2,2015-03-31,ACTIVE,NaN,01-03-2010,200,60.977413,60,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183001,183001,A2,2015-04-30,ACTIVE,NaN,01-03-2010,200,61.963039,61,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183002,183002,A2,2015-05-31,ACTIVE,NaN,01-03-2010,200,62.981520,62,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183003,183003,A2,2015-06-30,ACTIVE,NaN,01-03-2010,200,63.967146,63,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183004,183004,A2,2015-07-31,ACTIVE,NaN,01-03-2010,200,65.164036,64,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183005,183005,A2,2015-08-31,ACTIVE,NaN,01-03-2010,200,66.004107,65,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183006,183006,A2,2015-09-30,ACTIVE,NaN,01-03-2010,200,66.989733,66,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183007,183007,A2,2015-10-31,ACTIVE,NaN,01-03-2010,200,68.008214,67,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183008,183008,A2,2015-11-30,ACTIVE,NaN,01-03-2010,200,68.993840,68,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183009,183009,A2,2015-12-31,ACTIVE,NaN,01-03-2010,200,70.012320,69,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183010,183010,A2,2016-01-31,ACTIVE,NaN,01-03-2010,200,71.030801,70,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183011,183011,A2,2016-02-29,ACTIVE,NaN,01-03-2010,200,71.983573,71,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183012,183012,A2,2016-03-31,ACTIVE,NaN,01-03-2010,200,73.002053,72,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183013,183013,A2,2016-04-30,ACTIVE,NaN,01-03-2010,200,73.987680,73,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183014,183014,A2,2016-05-31,ACTIVE,NaN,01-03-2010,200,75.006160,74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,12
183015,183015,A2,2016-06-30,Active,NaN,01-03-2010,200,75.006200,75,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,3
183016,183016,A2,2016-07-31,ACTIVE,NaN,01-03-2010,200,77.010267,76,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,3
183017,183017,A2,2016-08-31,ACTIVE,NaN,01-03-2010,200,78.028747,77,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,3
183018,183018,A2,2016-09-30,LAPSED,NaN,01-03-2010,200,79.014374,78,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,3,3

In [14]:
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [15]:
data = data.fillna(0)

In [16]:
import datetime
import time
boundary_date = datetime.datetime.strptime('17-01-31', '%y-%m-%d').date()
mod_data = data[data.VALUATION < boundary_date]

In [17]:
train_data = mod_data.iloc[0:130000,:]
test_data = mod_data.iloc[130000:,:]
x_train = train_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
x_test = test_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
y_train = train_data[['y']]
y_test = test_data[['y']]
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)

/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[    0  1255]
 [    0 37952]]

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00      1255
         12       0.97      1.00      0.98     37952

avg / total       0.94      0.97      0.95     39207

/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [20]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [21]:
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[  324   931]
 [ 1488 36464]]

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          3       0.18      0.26      0.21      1255
         12       0.98      0.96      0.97     37952

avg / total       0.95      0.94      0.94     39207

In [77]:
maj_data = mod_data[mod_data.y>3]
maj_data = maj_data.iloc[0:18832 , :]
min_data = mod_data[mod_data.y<4]
frames = [maj_data , min_data]
balanced_data = pd.concat(frames)
balanced_data.shape

(25099, 63)

In [78]:
train_data = balanced_data.iloc[0:15000,:]
test_data = balanced_data.iloc[15000:,:]
x_train = train_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
x_test = test_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
y_train = train_data[['y']]
y_test = test_data[['y']]

In [79]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [80]:
y_pred = classifier.predict(x_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[   0 6267]
 [   0 3832]]

In [81]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00      6267
         12       0.38      1.00      0.55      3832

avg / total       0.14      0.38      0.21     10099

In [83]:
X = mod_data[['Tenure_Months','Apps_Proc_Percent','Applied_Premium','NoBenePercent','NoCertPercent','GROSS_AP','G0138_received','Setup_Complete','Total_Suspense','TotalCases','Active_Cases']]
y = mod_data[['y']]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [84]:
import xgboost as xgb
from xgboost.sklearn import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train,y_train)

/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [85]:
y_pred = classifier.predict(X_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[  328  1215]
 [   55 40704]]

/home/koushik/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [86]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          3       0.86      0.21      0.34      1543
         12       0.97      1.00      0.98     40759

avg / total       0.97      0.97      0.96     42302

In [ ]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)

In [ ]:
y_pred = svclassifier.predict(X_test)  
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print(classification_report(y_test, y_pred))