In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/home/koushik/Downloads/train_auto.csv")

In [3]:
data

,INDEX,TARGET_FLAG,TARGET_AMT,KIDSDRIV,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,...,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CAR_AGE,URBANICITY
0,1,0,0.000000,0,60.0,0,11.0,"$67,349",No,$0,...,"$14,230",11,Minivan,yes,"$4,461",2,No,3,18.0,Highly Urban/ Urban
1,2,0,0.000000,0,43.0,0,11.0,"$91,449",No,"$257,252",...,"$14,940",1,Minivan,yes,$0,0,No,0,1.0,Highly Urban/ Urban
2,4,0,0.000000,0,35.0,1,10.0,"$16,039",No,"$124,191",...,"$4,010",4,z_SUV,no,"$38,690",2,No,3,10.0,Highly Urban/ Urban
3,5,0,0.000000,0,51.0,0,14.0,NaN,No,"$306,251",...,"$15,440",7,Minivan,yes,$0,0,No,0,6.0,Highly Urban/ Urban
4,6,0,0.000000,0,50.0,0,NaN,"$114,986",No,"$243,925",...,"$18,000",1,z_SUV,no,"$19,217",2,Yes,3,17.0,Highly Urban/ Urban
5,7,1,2946.000000,0,34.0,1,12.0,"$125,301",Yes,$0,...,"$17,430",1,Sports Car,no,$0,0,No,0,7.0,Highly Urban/ Urban
6,8,0,0.000000,0,54.0,0,NaN,"$18,755",No,NaN,...,"$8,780",1,z_SUV,no,$0,0,No,0,1.0,Highly Urban/ Urban
7,11,1,4021.000000,1,37.0,2,NaN,"$107,961",No,"$333,680",...,"$16,970",1,Van,yes,"$2,374",1,Yes,10,7.0,Highly Urban/ Urban
8,12,1,2501.000000,0,34.0,0,10.0,"$62,978",No,$0,...,"$11,200",1,z_SUV,no,$0,0,No,0,1.0,Highly Urban/ Urban
9,13,0,0.000000,0,50.0,0,7.0,"$106,952",No,$0,...,"$18,510",7,Van,no,$0,0,No,1,17.0,z_Highly Rural/ Rural
10,14,1,6077.000000,0,53.0,0,14.0,"$77,100",No,$0,...,"$18,300",1,Sports Car,no,$0,0,No,0,11.0,Highly Urban/ Urban
11,15,0,0.000000,0,43.0,0,5.0,"$52,642",No,"$209,970",...,"$22,420",7,Minivan,no,$0,0,No,0,1.0,z_Highly Rural/ Rural
12,16,0,0.000000,0,55.0,0,11.0,"$59,162",No,"$180,232",...,"$17,600",7,Van,yes,"$5,028",2,Yes,3,9.0,Highly Urban/ Urban
13,17,1,1267.000000,0,53.0,0,11.0,"$130,795",No,$0,...,"$28,340",6,Panel Truck,yes,$0,0,No,3,10.0,Highly Urban/ Urban
14,19,1,2920.167320,0,45.0,0,0.0,$0,No,"$106,859",...,"$6,000",1,z_SUV,no,$0,0,No,3,5.0,Highly Urban/ Urban
15,20,0,0.000000,0,39.0,3,12.0,"$51,884",Yes,"$180,951",...,"$10,590",6,z_SUV,no,$0,0,No,0,13.0,z_Highly Rural/ Rural
16,22,0,0.000000,0,42.0,0,11.0,"$59,945",No,"$192,207",...,"$14,190",6,Minivan,no,$0,0,No,0,16.0,Highly Urban/ Urban
17,23,0,0.000000,0,34.0,3,13.0,"$34,019",No,"$91,875",...,"$8,300",7,z_SUV,no,$0,0,No,0,20.0,Highly Urban/ Urban
18,24,0,0.000000,0,31.0,2,12.0,"$18,903",No,"$93,797",...,"$17,330",4,Minivan,no,$0,0,No,0,7.0,Highly Urban/ Urban
19,25,1,6857.000000,0,28.0,1,13.0,"$44,077",No,"$170,598",...,"$8,710",6,z_SUV,no,"$8,935",2,No,0,1.0,Highly Urban/ Urban
20,26,1,3627.000000,0,43.0,0,13.0,"$37,214",No,NaN,...,"$26,560",1,Panel Truck,yes,$0,0,No,3,1.0,Highly Urban/ Urban
21,27,0,0.000000,0,48.0,0,14.0,"$96,274",No,"$282,904",...,"$11,130",6,z_SUV,no,"$8,250",1,No,5,14.0,Highly Urban/ Urban
22,28,0,0.000000,0,47.0,0,11.0,"$46,281",No,$0,...,"$19,700",10,Minivan,no,$0,0,No,1,5.0,Highly Urban/ Urban
23,29,0,0.000000,2,44.0,2,0.0,$0,No,"$82,344",...,"$5,900",6,z_SUV,no,"$3,338",3,No,0,11.0,Highly Urban/ Urban
24,32,0,0.000000,0,33.0,1,13.0,"$79,606",No,"$225,962",...,"$16,830",9,z_SUV,no,$0,0,No,2,15.0,z_Highly Rural/ Rural
25,33,1,4486.000000,0,32.0,1,9.0,"$31,275",No,"$118,160",...,"$10,030",1,z_SUV,no,$0,0,No,0,1.0,Highly Urban/ Urban
26,34,0,0.000000,1,44.0,2,17.0,"$45,488",No,"$219,378",...,"$22,090",17,Minivan,no,$0,0,No,0,12.0,Highly Urban/ Urban
27,35,0,0.000000,0,35.0,0,8.0,"$72,193",No,$0,...,"$12,220",6,z_SUV,no,$0,0,No,3,12.0,Highly Urban/ Urban
28,36,0,0.000000,0,40.0,2,0.0,NaN,No,"$98,777",...,"$14,130",6,z_SUV,no,"$38,127",2,Yes,4,12.0,z_Highly Rural/ Rural
29,38,0,0.000000,0,49.0,0,5.0,"$49,244",No,"$163,444",...,"$15,880",1,Minivan,no,$0,0,No,1,1.0,Highly Urban/ Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8131,10260,0,0.000000,0,56.0,0,13.0,"$52,130",No,"$176,831",...,"$12,310",3,z_SUV,no,"$10,494",2,No,3,4.0,Highly Urban/ Urban
8132,10261,1,3179.000000,0,47.0,0,NaN,"$112,264",No,$0,...,"$24,020",1,Panel Truck,yes,"$22,762",1,Yes,5,20.0,Highly Urban/ Urban
8133,10263,1,3106.000000,0,47.0,0,13.0,"$282,198",No,"$649,247",...,"$34,420",11,Panel Truck,yes,$0,0,Yes,2,16.0,Highly Urban/ Urban
8134,10265,1,471.115458,0,43.0,0,NaN,$0,No,"$55,203",...,"$24,030",9,Minivan,no,"$3,035",4,No,0,14.0,Highly Urban/ Urban
8135,10267,0,0.000000,1,45.0,1,14.0,"$1,956",Yes,$0,...,"$8,350",1,z_SUV,no,$0,0,No,0,1.0,z_Highly Rural/ Rural
8136,10269,0,0.000000,0,32.0,2,14.0,NaN,No,"$219,966",...,"$19,680",10,Van,no,$0,0,No,1,9.0,z_Highly Rural/ Rural
8137,10270,1,3135.000000,0,46.0,0,10.0,"$68,360",No,"$237,457",...,"$12,940",1,Minivan,no,"$6,560",3,No,7,11.0,Highly Urban/ Urban
8138,10273,0,0.000000,1,46.0,0,10.0,"$84,667",No,"$236,725",...,"$35,050",1,Panel Truck,no,$0,0,No,0,7.0,Highly Urban/ Urban
8139,10274,0,0.000000,0,48.0,0,12.0,"$66,613",No,"$209,239",...,"$16,340",6,z_SUV,no,$0,0,No,0,5.0,z_Highly Rural/ Rural
8140,10275,0,0.000000,0,56.0,0,11.0,"$12,917",No,NaN,...,"$2,790",4,z_SUV,no,$0,0,No,0,12.0,Highly Urban/ Urban
8141,10278,0,0.000000,0,35.0,0,7.0,"$64,890",No,$0,...,"$7,990",8,z_SUV,no,$0,0,No,1,12.0,Highly Urban/ Urban
8142,10280,0,0.000000,0,49.0,0,12.0,"$60,049",No,"$227,054",...,"$6,200",1,z_SUV,no,$0,0,No,0,1.0,z_Highly Rural/ Rural
8143,10282,0,0.000000,0,42.0,0,12.0,"$80,078",No,"$266,403",...,"$20,640",1,Minivan,no,$0,0,No,2,16.0,Highly Urban/ Urban
8144,10283,0,0.000000,0,36.0,2,13.0,"$131,335",Yes,"$352,524",...,"$28,490",1,Sports Car,no,$0,0,No,0,4.0,z_Highly Rural/ Rural
8145,10284,0,0.000000,0,38.0,3,8.0,"$83,458",Yes,"$232,182",...,"$28,260",6,Sports Car,no,"$9,298",2,No,3,9.0,Highly Urban/ Urban
8146,10286,1,1815.205097,0,41.0,0,12.0,"$92,185",No,"$289,370",...,"$1,500",11,Minivan,yes,$0,0,No,0,10.0,Highly Urban/ Urban
8147,10287,0,0.000000,0,60.0,0,12.0,"$19,796",No,"$153,061",...,"$21,690",1,Sports Car,no,"$2,800",2,No,4,1.0,Highly Urban/ Urban
8148,10288,1,2967.000000,0,45.0,0,11.0,"$52,966",No,$0,...,"$11,300",6,Pickup,yes,"$16,239",2,Yes,5,1.0,Highly Urban/ Urban
8149,10289,0,0.000000,0,54.0,0,11.0,"$69,111",No,"$291,969",...,"$16,510",1,Van,yes,"$5,038",1,No,3,1.0,Highly Urban/ Urban
8150,10290,0,0.000000,0,54.0,0,13.0,"$62,060",No,"$244,889",...,"$1,500",6,Minivan,no,$0,0,No,3,1.0,Highly Urban/ Urban
8151,10291,0,0.000000,0,54.0,0,13.0,"$81,818",No,"$272,725",...,"$19,660",1,Van,no,"$24,690",1,Yes,6,4.0,Highly Urban/ Urban
8152,10292,0,0.000000,1,46.0,0,12.0,"$45,018",No,$0,...,"$15,060",4,Minivan,no,"$33,026",3,No,0,1.0,z_Highly Rural/ Rural
8153,10293,0,0.000000,0,48.0,0,10.0,"$111,305",No,$0,...,"$17,430",13,z_SUV,no,$0,0,No,4,18.0,Highly Urban/ Urban
8154,10295,0,0.000000,1,38.0,4,16.0,"$12,717",No,$0,...,"$24,740",1,Pickup,no,"$9,245",3,No,3,15.0,Highly Urban/ Urban
8155,10296,0,0.000000,0,41.0,0,7.0,"$6,256",No,$0,...,"$5,600",1,Pickup,no,$0,0,No,0,7.0,z_Highly Rural/ Rural
8156,10297,0,0.000000,0,35.0,0,11.0,"$43,112",No,$0,...,"$27,330",10,Panel Truck,yes,$0,0,No,0,8.0,z_Highly Rural/ Rural
8157,10298,0,0.000000,1,45.0,2,9.0,"$164,669",No,"$386,273",...,"$13,270",15,Minivan,no,$0,0,No,2,17.0,Highly Urban/ Urban
8158,10299,0,0.000000,0,46.0,0,9.0,"$107,204",No,"$332,591",...,"$24,490",6,Panel Truck,no,$0,0,No,0,1.0,Highly Urban/ Urban
8159,10301,0,0.000000,0,50.0,0,7.0,"$43,445",No,"$149,248",...,"$22,550",6,Minivan,no,$0,0,No,0,11.0,Highly Urban/ Urban
8160,10302,0,0.000000,0,52.0,0,11.0,"$53,235",No,"$197,017",...,"$19,400",6,Minivan,no,$0,0,No,0,9.0,z_Highly Rural/ Rural

In [4]:
data.shape

(8161, 26)

In [8]:
data.iloc[:,2]

0          0.000000
1          0.000000
2          0.000000
3          0.000000
4          0.000000
5       2946.000000
6          0.000000
7       4021.000000
8       2501.000000
9          0.000000
10      6077.000000
11         0.000000
12         0.000000
13      1267.000000
14      2920.167320
15         0.000000
16         0.000000
17         0.000000
18         0.000000
19      6857.000000
20      3627.000000
21         0.000000
22         0.000000
23         0.000000
24         0.000000
25      4486.000000
26         0.000000
27         0.000000
28         0.000000
29         0.000000
           ...
8131       0.000000
8132    3179.000000
8133    3106.000000
8134     471.115458
8135       0.000000
8136       0.000000
8137    3135.000000
8138       0.000000
8139       0.000000
8140       0.000000
8141       0.000000
8142       0.000000
8143       0.000000
8144       0.000000
8145       0.000000
8146    1815.205097
8147       0.000000
8148    2967.000000
8149       0.000000
8150       0.000000
8151       0.000000
8152       0.000000
8153       0.000000
8154       0.000000
8155       0.000000
8156       0.000000
8157       0.000000
8158       0.000000
8159       0.000000
8160       0.000000
Name: TARGET_AMT, Length: 8161, dtype: float64

In [9]:
from sklearn import preprocessing

In [10]:
le = preprocessing.LabelEncoder()

In [23]:
le.fit(data['CAR_TYPE'])

LabelEncoder()

In [18]:
le.classes_

array(['Minivan', 'Panel Truck', 'Pickup', 'Sports Car', 'Van', 'z_SUV'],
      dtype=object)

In [20]:
car_dup = le.transform(data['CAR_TYPE'])

In [21]:
car_dup

array([0, 0, 5, ..., 1, 0, 0])

In [12]:
data['CAR_TYPE']

0           Minivan
1           Minivan
2             z_SUV
3           Minivan
4             z_SUV
5        Sports Car
6             z_SUV
7               Van
8             z_SUV
9               Van
10       Sports Car
11          Minivan
12              Van
13      Panel Truck
14            z_SUV
15            z_SUV
16          Minivan
17            z_SUV
18          Minivan
19            z_SUV
20      Panel Truck
21            z_SUV
22          Minivan
23            z_SUV
24            z_SUV
25            z_SUV
26          Minivan
27            z_SUV
28            z_SUV
29          Minivan
           ...
8131          z_SUV
8132    Panel Truck
8133    Panel Truck
8134        Minivan
8135          z_SUV
8136            Van
8137        Minivan
8138    Panel Truck
8139          z_SUV
8140          z_SUV
8141          z_SUV
8142          z_SUV
8143        Minivan
8144     Sports Car
8145     Sports Car
8146        Minivan
8147     Sports Car
8148         Pickup
8149            Van
8150        Minivan
8151            Van
8152        Minivan
8153          z_SUV
8154         Pickup
8155         Pickup
8156    Panel Truck
8157        Minivan
8158    Panel Truck
8159        Minivan
8160        Minivan
Name: CAR_TYPE, Length: 8161, dtype: object

In [24]:
data.columns

Index([u'INDEX', u'TARGET_FLAG', u'TARGET_AMT', u'KIDSDRIV', u'AGE',
       u'HOMEKIDS', u'YOJ', u'INCOME', u'PARENT1', u'HOME_VAL', u'MSTATUS',
       u'SEX', u'EDUCATION', u'JOB', u'TRAVTIME', u'CAR_USE', u'BLUEBOOK',
       u'TIF', u'CAR_TYPE', u'RED_CAR', u'OLDCLAIM', u'CLM_FREQ', u'REVOKED',
       u'MVR_PTS', u'CAR_AGE', u'URBANICITY'],
      dtype='object')

In [25]:
def myencode(data,column) : 
    le = preprocessing.LabelEncoder()
    le.fit(data[column])
    dup = le.transform(data[column])
    return dup

In [28]:
myencode(data,column='PARENT1')

array([0, 0, 0, ..., 0, 0, 0])

In [34]:
def myencodeAll(data,column) : 
    le = preprocessing.LabelEncoder()
    for col in column:
        le.fit(data[col])
        data[col] = le.transform(data[col])
    return data

In [39]:
myencodeAll(data,column=['PARENT1','CAR_TYPE','RED_CAR','REVOKED','URBANICITY'])

,INDEX,TARGET_FLAG,TARGET_AMT,KIDSDRIV,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,...,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CAR_AGE,URBANICITY
0,1,0,0.000000,0,60.0,0,11.0,"$67,349",0,$0,...,"$14,230",11,0,1,"$4,461",2,0,3,18.0,0
1,2,0,0.000000,0,43.0,0,11.0,"$91,449",0,"$257,252",...,"$14,940",1,0,1,$0,0,0,0,1.0,0
2,4,0,0.000000,0,35.0,1,10.0,"$16,039",0,"$124,191",...,"$4,010",4,5,0,"$38,690",2,0,3,10.0,0
3,5,0,0.000000,0,51.0,0,14.0,NaN,0,"$306,251",...,"$15,440",7,0,1,$0,0,0,0,6.0,0
4,6,0,0.000000,0,50.0,0,NaN,"$114,986",0,"$243,925",...,"$18,000",1,5,0,"$19,217",2,1,3,17.0,0
5,7,1,2946.000000,0,34.0,1,12.0,"$125,301",1,$0,...,"$17,430",1,3,0,$0,0,0,0,7.0,0
6,8,0,0.000000,0,54.0,0,NaN,"$18,755",0,NaN,...,"$8,780",1,5,0,$0,0,0,0,1.0,0
7,11,1,4021.000000,1,37.0,2,NaN,"$107,961",0,"$333,680",...,"$16,970",1,4,1,"$2,374",1,1,10,7.0,0
8,12,1,2501.000000,0,34.0,0,10.0,"$62,978",0,$0,...,"$11,200",1,5,0,$0,0,0,0,1.0,0
9,13,0,0.000000,0,50.0,0,7.0,"$106,952",0,$0,...,"$18,510",7,4,0,$0,0,0,1,17.0,1
10,14,1,6077.000000,0,53.0,0,14.0,"$77,100",0,$0,...,"$18,300",1,3,0,$0,0,0,0,11.0,0
11,15,0,0.000000,0,43.0,0,5.0,"$52,642",0,"$209,970",...,"$22,420",7,0,0,$0,0,0,0,1.0,1
12,16,0,0.000000,0,55.0,0,11.0,"$59,162",0,"$180,232",...,"$17,600",7,4,1,"$5,028",2,1,3,9.0,0
13,17,1,1267.000000,0,53.0,0,11.0,"$130,795",0,$0,...,"$28,340",6,1,1,$0,0,0,3,10.0,0
14,19,1,2920.167320,0,45.0,0,0.0,$0,0,"$106,859",...,"$6,000",1,5,0,$0,0,0,3,5.0,0
15,20,0,0.000000,0,39.0,3,12.0,"$51,884",1,"$180,951",...,"$10,590",6,5,0,$0,0,0,0,13.0,1
16,22,0,0.000000,0,42.0,0,11.0,"$59,945",0,"$192,207",...,"$14,190",6,0,0,$0,0,0,0,16.0,0
17,23,0,0.000000,0,34.0,3,13.0,"$34,019",0,"$91,875",...,"$8,300",7,5,0,$0,0,0,0,20.0,0
18,24,0,0.000000,0,31.0,2,12.0,"$18,903",0,"$93,797",...,"$17,330",4,0,0,$0,0,0,0,7.0,0
19,25,1,6857.000000,0,28.0,1,13.0,"$44,077",0,"$170,598",...,"$8,710",6,5,0,"$8,935",2,0,0,1.0,0
20,26,1,3627.000000,0,43.0,0,13.0,"$37,214",0,NaN,...,"$26,560",1,1,1,$0,0,0,3,1.0,0
21,27,0,0.000000,0,48.0,0,14.0,"$96,274",0,"$282,904",...,"$11,130",6,5,0,"$8,250",1,0,5,14.0,0
22,28,0,0.000000,0,47.0,0,11.0,"$46,281",0,$0,...,"$19,700",10,0,0,$0,0,0,1,5.0,0
23,29,0,0.000000,2,44.0,2,0.0,$0,0,"$82,344",...,"$5,900",6,5,0,"$3,338",3,0,0,11.0,0
24,32,0,0.000000,0,33.0,1,13.0,"$79,606",0,"$225,962",...,"$16,830",9,5,0,$0,0,0,2,15.0,1
25,33,1,4486.000000,0,32.0,1,9.0,"$31,275",0,"$118,160",...,"$10,030",1,5,0,$0,0,0,0,1.0,0
26,34,0,0.000000,1,44.0,2,17.0,"$45,488",0,"$219,378",...,"$22,090",17,0,0,$0,0,0,0,12.0,0
27,35,0,0.000000,0,35.0,0,8.0,"$72,193",0,$0,...,"$12,220",6,5,0,$0,0,0,3,12.0,0
28,36,0,0.000000,0,40.0,2,0.0,NaN,0,"$98,777",...,"$14,130",6,5,0,"$38,127",2,1,4,12.0,1
29,38,0,0.000000,0,49.0,0,5.0,"$49,244",0,"$163,444",...,"$15,880",1,0,0,$0,0,0,1,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8131,10260,0,0.000000,0,56.0,0,13.0,"$52,130",0,"$176,831",...,"$12,310",3,5,0,"$10,494",2,0,3,4.0,0
8132,10261,1,3179.000000,0,47.0,0,NaN,"$112,264",0,$0,...,"$24,020",1,1,1,"$22,762",1,1,5,20.0,0
8133,10263,1,3106.000000,0,47.0,0,13.0,"$282,198",0,"$649,247",...,"$34,420",11,1,1,$0,0,1,2,16.0,0
8134,10265,1,471.115458,0,43.0,0,NaN,$0,0,"$55,203",...,"$24,030",9,0,0,"$3,035",4,0,0,14.0,0
8135,10267,0,0.000000,1,45.0,1,14.0,"$1,956",1,$0,...,"$8,350",1,5,0,$0,0,0,0,1.0,1
8136,10269,0,0.000000,0,32.0,2,14.0,NaN,0,"$219,966",...,"$19,680",10,4,0,$0,0,0,1,9.0,1
8137,10270,1,3135.000000,0,46.0,0,10.0,"$68,360",0,"$237,457",...,"$12,940",1,0,0,"$6,560",3,0,7,11.0,0
8138,10273,0,0.000000,1,46.0,0,10.0,"$84,667",0,"$236,725",...,"$35,050",1,1,0,$0,0,0,0,7.0,0
8139,10274,0,0.000000,0,48.0,0,12.0,"$66,613",0,"$209,239",...,"$16,340",6,5,0,$0,0,0,0,5.0,1
8140,10275,0,0.000000,0,56.0,0,11.0,"$12,917",0,NaN,...,"$2,790",4,5,0,$0,0,0,0,12.0,0
8141,10278,0,0.000000,0,35.0,0,7.0,"$64,890",0,$0,...,"$7,990",8,5,0,$0,0,0,1,12.0,0
8142,10280,0,0.000000,0,49.0,0,12.0,"$60,049",0,"$227,054",...,"$6,200",1,5,0,$0,0,0,0,1.0,1
8143,10282,0,0.000000,0,42.0,0,12.0,"$80,078",0,"$266,403",...,"$20,640",1,0,0,$0,0,0,2,16.0,0
8144,10283,0,0.000000,0,36.0,2,13.0,"$131,335",1,"$352,524",...,"$28,490",1,3,0,$0,0,0,0,4.0,1
8145,10284,0,0.000000,0,38.0,3,8.0,"$83,458",1,"$232,182",...,"$28,260",6,3,0,"$9,298",2,0,3,9.0,0
8146,10286,1,1815.205097,0,41.0,0,12.0,"$92,185",0,"$289,370",...,"$1,500",11,0,1,$0,0,0,0,10.0,0
8147,10287,0,0.000000,0,60.0,0,12.0,"$19,796",0,"$153,061",...,"$21,690",1,3,0,"$2,800",2,0,4,1.0,0
8148,10288,1,2967.000000,0,45.0,0,11.0,"$52,966",0,$0,...,"$11,300",6,2,1,"$16,239",2,1,5,1.0,0
8149,10289,0,0.000000,0,54.0,0,11.0,"$69,111",0,"$291,969",...,"$16,510",1,4,1,"$5,038",1,0,3,1.0,0
8150,10290,0,0.000000,0,54.0,0,13.0,"$62,060",0,"$244,889",...,"$1,500",6,0,0,$0,0,0,3,1.0,0
8151,10291,0,0.000000,0,54.0,0,13.0,"$81,818",0,"$272,725",...,"$19,660",1,4,0,"$24,690",1,1,6,4.0,0
8152,10292,0,0.000000,1,46.0,0,12.0,"$45,018",0,$0,...,"$15,060",4,0,0,"$33,026",3,0,0,1.0,1
8153,10293,0,0.000000,0,48.0,0,10.0,"$111,305",0,$0,...,"$17,430",13,5,0,$0,0,0,4,18.0,0
8154,10295,0,0.000000,1,38.0,4,16.0,"$12,717",0,$0,...,"$24,740",1,2,0,"$9,245",3,0,3,15.0,0
8155,10296,0,0.000000,0,41.0,0,7.0,"$6,256",0,$0,...,"$5,600",1,2,0,$0,0,0,0,7.0,1
8156,10297,0,0.000000,0,35.0,0,11.0,"$43,112",0,$0,...,"$27,330",10,1,1,$0,0,0,0,8.0,1
8157,10298,0,0.000000,1,45.0,2,9.0,"$164,669",0,"$386,273",...,"$13,270",15,0,0,$0,0,0,2,17.0,0
8158,10299,0,0.000000,0,46.0,0,9.0,"$107,204",0,"$332,591",...,"$24,490",6,1,0,$0,0,0,0,1.0,0
8159,10301,0,0.000000,0,50.0,0,7.0,"$43,445",0,"$149,248",...,"$22,550",6,0,0,$0,0,0,0,11.0,0
8160,10302,0,0.000000,0,52.0,0,11.0,"$53,235",0,"$197,017",...,"$19,400",6,0,0,$0,0,0,0,9.0,1

In [31]:
COLS=['A','B']

In [32]:
COLS[1]

'B'

In [33]:
for xyz in COLS:
    print xyz

A
B

In [50]:
data.fillna(data.mean())

,INDEX,TARGET_FLAG,TARGET_AMT,KIDSDRIV,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,...,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CAR_AGE,URBANICITY
0,1,0,0.000000,0,60.0,0,11.000000,"$67,349",0,$0,...,"$14,230",11,0,1,"$4,461",2,0,3,18.0,0
1,2,0,0.000000,0,43.0,0,11.000000,"$91,449",0,"$257,252",...,"$14,940",1,0,1,$0,0,0,0,1.0,0
2,4,0,0.000000,0,35.0,1,10.000000,"$16,039",0,"$124,191",...,"$4,010",4,5,0,"$38,690",2,0,3,10.0,0
3,5,0,0.000000,0,51.0,0,14.000000,NaN,0,"$306,251",...,"$15,440",7,0,1,$0,0,0,0,6.0,0
4,6,0,0.000000,0,50.0,0,10.499286,"$114,986",0,"$243,925",...,"$18,000",1,5,0,"$19,217",2,1,3,17.0,0
5,7,1,2946.000000,0,34.0,1,12.000000,"$125,301",1,$0,...,"$17,430",1,3,0,$0,0,0,0,7.0,0
6,8,0,0.000000,0,54.0,0,10.499286,"$18,755",0,NaN,...,"$8,780",1,5,0,$0,0,0,0,1.0,0
7,11,1,4021.000000,1,37.0,2,10.499286,"$107,961",0,"$333,680",...,"$16,970",1,4,1,"$2,374",1,1,10,7.0,0
8,12,1,2501.000000,0,34.0,0,10.000000,"$62,978",0,$0,...,"$11,200",1,5,0,$0,0,0,0,1.0,0
9,13,0,0.000000,0,50.0,0,7.000000,"$106,952",0,$0,...,"$18,510",7,4,0,$0,0,0,1,17.0,1
10,14,1,6077.000000,0,53.0,0,14.000000,"$77,100",0,$0,...,"$18,300",1,3,0,$0,0,0,0,11.0,0
11,15,0,0.000000,0,43.0,0,5.000000,"$52,642",0,"$209,970",...,"$22,420",7,0,0,$0,0,0,0,1.0,1
12,16,0,0.000000,0,55.0,0,11.000000,"$59,162",0,"$180,232",...,"$17,600",7,4,1,"$5,028",2,1,3,9.0,0
13,17,1,1267.000000,0,53.0,0,11.000000,"$130,795",0,$0,...,"$28,340",6,1,1,$0,0,0,3,10.0,0
14,19,1,2920.167320,0,45.0,0,0.000000,$0,0,"$106,859",...,"$6,000",1,5,0,$0,0,0,3,5.0,0
15,20,0,0.000000,0,39.0,3,12.000000,"$51,884",1,"$180,951",...,"$10,590",6,5,0,$0,0,0,0,13.0,1
16,22,0,0.000000,0,42.0,0,11.000000,"$59,945",0,"$192,207",...,"$14,190",6,0,0,$0,0,0,0,16.0,0
17,23,0,0.000000,0,34.0,3,13.000000,"$34,019",0,"$91,875",...,"$8,300",7,5,0,$0,0,0,0,20.0,0
18,24,0,0.000000,0,31.0,2,12.000000,"$18,903",0,"$93,797",...,"$17,330",4,0,0,$0,0,0,0,7.0,0
19,25,1,6857.000000,0,28.0,1,13.000000,"$44,077",0,"$170,598",...,"$8,710",6,5,0,"$8,935",2,0,0,1.0,0
20,26,1,3627.000000,0,43.0,0,13.000000,"$37,214",0,NaN,...,"$26,560",1,1,1,$0,0,0,3,1.0,0
21,27,0,0.000000,0,48.0,0,14.000000,"$96,274",0,"$282,904",...,"$11,130",6,5,0,"$8,250",1,0,5,14.0,0
22,28,0,0.000000,0,47.0,0,11.000000,"$46,281",0,$0,...,"$19,700",10,0,0,$0,0,0,1,5.0,0
23,29,0,0.000000,2,44.0,2,0.000000,$0,0,"$82,344",...,"$5,900",6,5,0,"$3,338",3,0,0,11.0,0
24,32,0,0.000000,0,33.0,1,13.000000,"$79,606",0,"$225,962",...,"$16,830",9,5,0,$0,0,0,2,15.0,1
25,33,1,4486.000000,0,32.0,1,9.000000,"$31,275",0,"$118,160",...,"$10,030",1,5,0,$0,0,0,0,1.0,0
26,34,0,0.000000,1,44.0,2,17.000000,"$45,488",0,"$219,378",...,"$22,090",17,0,0,$0,0,0,0,12.0,0
27,35,0,0.000000,0,35.0,0,8.000000,"$72,193",0,$0,...,"$12,220",6,5,0,$0,0,0,3,12.0,0
28,36,0,0.000000,0,40.0,2,0.000000,NaN,0,"$98,777",...,"$14,130",6,5,0,"$38,127",2,1,4,12.0,1
29,38,0,0.000000,0,49.0,0,5.000000,"$49,244",0,"$163,444",...,"$15,880",1,0,0,$0,0,0,1,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8131,10260,0,0.000000,0,56.0,0,13.000000,"$52,130",0,"$176,831",...,"$12,310",3,5,0,"$10,494",2,0,3,4.0,0
8132,10261,1,3179.000000,0,47.0,0,10.499286,"$112,264",0,$0,...,"$24,020",1,1,1,"$22,762",1,1,5,20.0,0
8133,10263,1,3106.000000,0,47.0,0,13.000000,"$282,198",0,"$649,247",...,"$34,420",11,1,1,$0,0,1,2,16.0,0
8134,10265,1,471.115458,0,43.0,0,10.499286,$0,0,"$55,203",...,"$24,030",9,0,0,"$3,035",4,0,0,14.0,0
8135,10267,0,0.000000,1,45.0,1,14.000000,"$1,956",1,$0,...,"$8,350",1,5,0,$0,0,0,0,1.0,1
8136,10269,0,0.000000,0,32.0,2,14.000000,NaN,0,"$219,966",...,"$19,680",10,4,0,$0,0,0,1,9.0,1
8137,10270,1,3135.000000,0,46.0,0,10.000000,"$68,360",0,"$237,457",...,"$12,940",1,0,0,"$6,560",3,0,7,11.0,0
8138,10273,0,0.000000,1,46.0,0,10.000000,"$84,667",0,"$236,725",...,"$35,050",1,1,0,$0,0,0,0,7.0,0
8139,10274,0,0.000000,0,48.0,0,12.000000,"$66,613",0,"$209,239",...,"$16,340",6,5,0,$0,0,0,0,5.0,1
8140,10275,0,0.000000,0,56.0,0,11.000000,"$12,917",0,NaN,...,"$2,790",4,5,0,$0,0,0,0,12.0,0
8141,10278,0,0.000000,0,35.0,0,7.000000,"$64,890",0,$0,...,"$7,990",8,5,0,$0,0,0,1,12.0,0
8142,10280,0,0.000000,0,49.0,0,12.000000,"$60,049",0,"$227,054",...,"$6,200",1,5,0,$0,0,0,0,1.0,1
8143,10282,0,0.000000,0,42.0,0,12.000000,"$80,078",0,"$266,403",...,"$20,640",1,0,0,$0,0,0,2,16.0,0
8144,10283,0,0.000000,0,36.0,2,13.000000,"$131,335",1,"$352,524",...,"$28,490",1,3,0,$0,0,0,0,4.0,1
8145,10284,0,0.000000,0,38.0,3,8.000000,"$83,458",1,"$232,182",...,"$28,260",6,3,0,"$9,298",2,0,3,9.0,0
8146,10286,1,1815.205097,0,41.0,0,12.000000,"$92,185",0,"$289,370",...,"$1,500",11,0,1,$0,0,0,0,10.0,0
8147,10287,0,0.000000,0,60.0,0,12.000000,"$19,796",0,"$153,061",...,"$21,690",1,3,0,"$2,800",2,0,4,1.0,0
8148,10288,1,2967.000000,0,45.0,0,11.000000,"$52,966",0,$0,...,"$11,300",6,2,1,"$16,239",2,1,5,1.0,0
8149,10289,0,0.000000,0,54.0,0,11.000000,"$69,111",0,"$291,969",...,"$16,510",1,4,1,"$5,038",1,0,3,1.0,0
8150,10290,0,0.000000,0,54.0,0,13.000000,"$62,060",0,"$244,889",...,"$1,500",6,0,0,$0,0,0,3,1.0,0
8151,10291,0,0.000000,0,54.0,0,13.000000,"$81,818",0,"$272,725",...,"$19,660",1,4,0,"$24,690",1,1,6,4.0,0
8152,10292,0,0.000000,1,46.0,0,12.000000,"$45,018",0,$0,...,"$15,060",4,0,0,"$33,026",3,0,0,1.0,1
8153,10293,0,0.000000,0,48.0,0,10.000000,"$111,305",0,$0,...,"$17,430",13,5,0,$0,0,0,4,18.0,0
8154,10295,0,0.000000,1,38.0,4,16.000000,"$12,717",0,$0,...,"$24,740",1,2,0,"$9,245",3,0,3,15.0,0
8155,10296,0,0.000000,0,41.0,0,7.000000,"$6,256",0,$0,...,"$5,600",1,2,0,$0,0,0,0,7.0,1
8156,10297,0,0.000000,0,35.0,0,11.000000,"$43,112",0,$0,...,"$27,330",10,1,1,$0,0,0,0,8.0,1
8157,10298,0,0.000000,1,45.0,2,9.000000,"$164,669",0,"$386,273",...,"$13,270",15,0,0,$0,0,0,2,17.0,0
8158,10299,0,0.000000,0,46.0,0,9.000000,"$107,204",0,"$332,591",...,"$24,490",6,1,0,$0,0,0,0,1.0,0
8159,10301,0,0.000000,0,50.0,0,7.000000,"$43,445",0,"$149,248",...,"$22,550",6,0,0,$0,0,0,0,11.0,0
8160,10302,0,0.000000,0,52.0,0,11.000000,"$53,235",0,"$197,017",...,"$19,400",6,0,0,$0,0,0,0,9.0,1

In [53]:
data.mean()

INDEX          5151.867663
TARGET_FLAG       0.263816
TARGET_AMT     1504.324648
KIDSDRIV          0.171057
AGE              44.790313
HOMEKIDS          0.721235
YOJ              10.499286
PARENT1           0.131969
TRAVTIME         33.485725
TIF               5.351305
CAR_TYPE          2.529714
RED_CAR           0.291386
CLM_FREQ          0.798554
REVOKED           0.122534
MVR_PTS           1.695503
CAR_AGE           8.328323
URBANICITY        0.204509
dtype: float64

In [55]:
data = data.fillna(data.mean())

In [56]:
data

,INDEX,TARGET_FLAG,TARGET_AMT,KIDSDRIV,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,...,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CAR_AGE,URBANICITY
0,1,0,0.000000,0,60.0,0,11.000000,"$67,349",0,$0,...,"$14,230",11,0,1,"$4,461",2,0,3,18.0,0
1,2,0,0.000000,0,43.0,0,11.000000,"$91,449",0,"$257,252",...,"$14,940",1,0,1,$0,0,0,0,1.0,0
2,4,0,0.000000,0,35.0,1,10.000000,"$16,039",0,"$124,191",...,"$4,010",4,5,0,"$38,690",2,0,3,10.0,0
3,5,0,0.000000,0,51.0,0,14.000000,NaN,0,"$306,251",...,"$15,440",7,0,1,$0,0,0,0,6.0,0
4,6,0,0.000000,0,50.0,0,10.499286,"$114,986",0,"$243,925",...,"$18,000",1,5,0,"$19,217",2,1,3,17.0,0
5,7,1,2946.000000,0,34.0,1,12.000000,"$125,301",1,$0,...,"$17,430",1,3,0,$0,0,0,0,7.0,0
6,8,0,0.000000,0,54.0,0,10.499286,"$18,755",0,NaN,...,"$8,780",1,5,0,$0,0,0,0,1.0,0
7,11,1,4021.000000,1,37.0,2,10.499286,"$107,961",0,"$333,680",...,"$16,970",1,4,1,"$2,374",1,1,10,7.0,0
8,12,1,2501.000000,0,34.0,0,10.000000,"$62,978",0,$0,...,"$11,200",1,5,0,$0,0,0,0,1.0,0
9,13,0,0.000000,0,50.0,0,7.000000,"$106,952",0,$0,...,"$18,510",7,4,0,$0,0,0,1,17.0,1
10,14,1,6077.000000,0,53.0,0,14.000000,"$77,100",0,$0,...,"$18,300",1,3,0,$0,0,0,0,11.0,0
11,15,0,0.000000,0,43.0,0,5.000000,"$52,642",0,"$209,970",...,"$22,420",7,0,0,$0,0,0,0,1.0,1
12,16,0,0.000000,0,55.0,0,11.000000,"$59,162",0,"$180,232",...,"$17,600",7,4,1,"$5,028",2,1,3,9.0,0
13,17,1,1267.000000,0,53.0,0,11.000000,"$130,795",0,$0,...,"$28,340",6,1,1,$0,0,0,3,10.0,0
14,19,1,2920.167320,0,45.0,0,0.000000,$0,0,"$106,859",...,"$6,000",1,5,0,$0,0,0,3,5.0,0
15,20,0,0.000000,0,39.0,3,12.000000,"$51,884",1,"$180,951",...,"$10,590",6,5,0,$0,0,0,0,13.0,1
16,22,0,0.000000,0,42.0,0,11.000000,"$59,945",0,"$192,207",...,"$14,190",6,0,0,$0,0,0,0,16.0,0
17,23,0,0.000000,0,34.0,3,13.000000,"$34,019",0,"$91,875",...,"$8,300",7,5,0,$0,0,0,0,20.0,0
18,24,0,0.000000,0,31.0,2,12.000000,"$18,903",0,"$93,797",...,"$17,330",4,0,0,$0,0,0,0,7.0,0
19,25,1,6857.000000,0,28.0,1,13.000000,"$44,077",0,"$170,598",...,"$8,710",6,5,0,"$8,935",2,0,0,1.0,0
20,26,1,3627.000000,0,43.0,0,13.000000,"$37,214",0,NaN,...,"$26,560",1,1,1,$0,0,0,3,1.0,0
21,27,0,0.000000,0,48.0,0,14.000000,"$96,274",0,"$282,904",...,"$11,130",6,5,0,"$8,250",1,0,5,14.0,0
22,28,0,0.000000,0,47.0,0,11.000000,"$46,281",0,$0,...,"$19,700",10,0,0,$0,0,0,1,5.0,0
23,29,0,0.000000,2,44.0,2,0.000000,$0,0,"$82,344",...,"$5,900",6,5,0,"$3,338",3,0,0,11.0,0
24,32,0,0.000000,0,33.0,1,13.000000,"$79,606",0,"$225,962",...,"$16,830",9,5,0,$0,0,0,2,15.0,1
25,33,1,4486.000000,0,32.0,1,9.000000,"$31,275",0,"$118,160",...,"$10,030",1,5,0,$0,0,0,0,1.0,0
26,34,0,0.000000,1,44.0,2,17.000000,"$45,488",0,"$219,378",...,"$22,090",17,0,0,$0,0,0,0,12.0,0
27,35,0,0.000000,0,35.0,0,8.000000,"$72,193",0,$0,...,"$12,220",6,5,0,$0,0,0,3,12.0,0
28,36,0,0.000000,0,40.0,2,0.000000,NaN,0,"$98,777",...,"$14,130",6,5,0,"$38,127",2,1,4,12.0,1
29,38,0,0.000000,0,49.0,0,5.000000,"$49,244",0,"$163,444",...,"$15,880",1,0,0,$0,0,0,1,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8131,10260,0,0.000000,0,56.0,0,13.000000,"$52,130",0,"$176,831",...,"$12,310",3,5,0,"$10,494",2,0,3,4.0,0
8132,10261,1,3179.000000,0,47.0,0,10.499286,"$112,264",0,$0,...,"$24,020",1,1,1,"$22,762",1,1,5,20.0,0
8133,10263,1,3106.000000,0,47.0,0,13.000000,"$282,198",0,"$649,247",...,"$34,420",11,1,1,$0,0,1,2,16.0,0
8134,10265,1,471.115458,0,43.0,0,10.499286,$0,0,"$55,203",...,"$24,030",9,0,0,"$3,035",4,0,0,14.0,0
8135,10267,0,0.000000,1,45.0,1,14.000000,"$1,956",1,$0,...,"$8,350",1,5,0,$0,0,0,0,1.0,1
8136,10269,0,0.000000,0,32.0,2,14.000000,NaN,0,"$219,966",...,"$19,680",10,4,0,$0,0,0,1,9.0,1
8137,10270,1,3135.000000,0,46.0,0,10.000000,"$68,360",0,"$237,457",...,"$12,940",1,0,0,"$6,560",3,0,7,11.0,0
8138,10273,0,0.000000,1,46.0,0,10.000000,"$84,667",0,"$236,725",...,"$35,050",1,1,0,$0,0,0,0,7.0,0
8139,10274,0,0.000000,0,48.0,0,12.000000,"$66,613",0,"$209,239",...,"$16,340",6,5,0,$0,0,0,0,5.0,1
8140,10275,0,0.000000,0,56.0,0,11.000000,"$12,917",0,NaN,...,"$2,790",4,5,0,$0,0,0,0,12.0,0
8141,10278,0,0.000000,0,35.0,0,7.000000,"$64,890",0,$0,...,"$7,990",8,5,0,$0,0,0,1,12.0,0
8142,10280,0,0.000000,0,49.0,0,12.000000,"$60,049",0,"$227,054",...,"$6,200",1,5,0,$0,0,0,0,1.0,1
8143,10282,0,0.000000,0,42.0,0,12.000000,"$80,078",0,"$266,403",...,"$20,640",1,0,0,$0,0,0,2,16.0,0
8144,10283,0,0.000000,0,36.0,2,13.000000,"$131,335",1,"$352,524",...,"$28,490",1,3,0,$0,0,0,0,4.0,1
8145,10284,0,0.000000,0,38.0,3,8.000000,"$83,458",1,"$232,182",...,"$28,260",6,3,0,"$9,298",2,0,3,9.0,0
8146,10286,1,1815.205097,0,41.0,0,12.000000,"$92,185",0,"$289,370",...,"$1,500",11,0,1,$0,0,0,0,10.0,0
8147,10287,0,0.000000,0,60.0,0,12.000000,"$19,796",0,"$153,061",...,"$21,690",1,3,0,"$2,800",2,0,4,1.0,0
8148,10288,1,2967.000000,0,45.0,0,11.000000,"$52,966",0,$0,...,"$11,300",6,2,1,"$16,239",2,1,5,1.0,0
8149,10289,0,0.000000,0,54.0,0,11.000000,"$69,111",0,"$291,969",...,"$16,510",1,4,1,"$5,038",1,0,3,1.0,0
8150,10290,0,0.000000,0,54.0,0,13.000000,"$62,060",0,"$244,889",...,"$1,500",6,0,0,$0,0,0,3,1.0,0
8151,10291,0,0.000000,0,54.0,0,13.000000,"$81,818",0,"$272,725",...,"$19,660",1,4,0,"$24,690",1,1,6,4.0,0
8152,10292,0,0.000000,1,46.0,0,12.000000,"$45,018",0,$0,...,"$15,060",4,0,0,"$33,026",3,0,0,1.0,1
8153,10293,0,0.000000,0,48.0,0,10.000000,"$111,305",0,$0,...,"$17,430",13,5,0,$0,0,0,4,18.0,0
8154,10295,0,0.000000,1,38.0,4,16.000000,"$12,717",0,$0,...,"$24,740",1,2,0,"$9,245",3,0,3,15.0,0
8155,10296,0,0.000000,0,41.0,0,7.000000,"$6,256",0,$0,...,"$5,600",1,2,0,$0,0,0,0,7.0,1
8156,10297,0,0.000000,0,35.0,0,11.000000,"$43,112",0,$0,...,"$27,330",10,1,1,$0,0,0,0,8.0,1
8157,10298,0,0.000000,1,45.0,2,9.000000,"$164,669",0,"$386,273",...,"$13,270",15,0,0,$0,0,0,2,17.0,0
8158,10299,0,0.000000,0,46.0,0,9.000000,"$107,204",0,"$332,591",...,"$24,490",6,1,0,$0,0,0,0,1.0,0
8159,10301,0,0.000000,0,50.0,0,7.000000,"$43,445",0,"$149,248",...,"$22,550",6,0,0,$0,0,0,0,11.0,0
8160,10302,0,0.000000,0,52.0,0,11.000000,"$53,235",0,"$197,017",...,"$19,400",6,0,0,$0,0,0,0,9.0,1

In [83]:
data.INCOME=data.INCOME.str.replace('$','')

In [87]:
data.INCOME=data.INCOME.str.replace(',','')

In [88]:
data

,INDEX,TARGET_FLAG,TARGET_AMT,KIDSDRIV,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,...,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CAR_AGE,URBANICITY
0,1,0,0.000000,0,60.0,0,11.000000,67349,0,$0,...,"$14,230",11,0,1,"$4,461",2,0,3,18.0,0
1,2,0,0.000000,0,43.0,0,11.000000,91449,0,"$257,252",...,"$14,940",1,0,1,$0,0,0,0,1.0,0
2,4,0,0.000000,0,35.0,1,10.000000,16039,0,"$124,191",...,"$4,010",4,5,0,"$38,690",2,0,3,10.0,0
3,5,0,0.000000,0,51.0,0,14.000000,NaN,0,"$306,251",...,"$15,440",7,0,1,$0,0,0,0,6.0,0
4,6,0,0.000000,0,50.0,0,10.499286,114986,0,"$243,925",...,"$18,000",1,5,0,"$19,217",2,1,3,17.0,0
5,7,1,2946.000000,0,34.0,1,12.000000,125301,1,$0,...,"$17,430",1,3,0,$0,0,0,0,7.0,0
6,8,0,0.000000,0,54.0,0,10.499286,18755,0,NaN,...,"$8,780",1,5,0,$0,0,0,0,1.0,0
7,11,1,4021.000000,1,37.0,2,10.499286,107961,0,"$333,680",...,"$16,970",1,4,1,"$2,374",1,1,10,7.0,0
8,12,1,2501.000000,0,34.0,0,10.000000,62978,0,$0,...,"$11,200",1,5,0,$0,0,0,0,1.0,0
9,13,0,0.000000,0,50.0,0,7.000000,106952,0,$0,...,"$18,510",7,4,0,$0,0,0,1,17.0,1
10,14,1,6077.000000,0,53.0,0,14.000000,77100,0,$0,...,"$18,300",1,3,0,$0,0,0,0,11.0,0
11,15,0,0.000000,0,43.0,0,5.000000,52642,0,"$209,970",...,"$22,420",7,0,0,$0,0,0,0,1.0,1
12,16,0,0.000000,0,55.0,0,11.000000,59162,0,"$180,232",...,"$17,600",7,4,1,"$5,028",2,1,3,9.0,0
13,17,1,1267.000000,0,53.0,0,11.000000,130795,0,$0,...,"$28,340",6,1,1,$0,0,0,3,10.0,0
14,19,1,2920.167320,0,45.0,0,0.000000,0,0,"$106,859",...,"$6,000",1,5,0,$0,0,0,3,5.0,0
15,20,0,0.000000,0,39.0,3,12.000000,51884,1,"$180,951",...,"$10,590",6,5,0,$0,0,0,0,13.0,1
16,22,0,0.000000,0,42.0,0,11.000000,59945,0,"$192,207",...,"$14,190",6,0,0,$0,0,0,0,16.0,0
17,23,0,0.000000,0,34.0,3,13.000000,34019,0,"$91,875",...,"$8,300",7,5,0,$0,0,0,0,20.0,0
18,24,0,0.000000,0,31.0,2,12.000000,18903,0,"$93,797",...,"$17,330",4,0,0,$0,0,0,0,7.0,0
19,25,1,6857.000000,0,28.0,1,13.000000,44077,0,"$170,598",...,"$8,710",6,5,0,"$8,935",2,0,0,1.0,0
20,26,1,3627.000000,0,43.0,0,13.000000,37214,0,NaN,...,"$26,560",1,1,1,$0,0,0,3,1.0,0
21,27,0,0.000000,0,48.0,0,14.000000,96274,0,"$282,904",...,"$11,130",6,5,0,"$8,250",1,0,5,14.0,0
22,28,0,0.000000,0,47.0,0,11.000000,46281,0,$0,...,"$19,700",10,0,0,$0,0,0,1,5.0,0
23,29,0,0.000000,2,44.0,2,0.000000,0,0,"$82,344",...,"$5,900",6,5,0,"$3,338",3,0,0,11.0,0
24,32,0,0.000000,0,33.0,1,13.000000,79606,0,"$225,962",...,"$16,830",9,5,0,$0,0,0,2,15.0,1
25,33,1,4486.000000,0,32.0,1,9.000000,31275,0,"$118,160",...,"$10,030",1,5,0,$0,0,0,0,1.0,0
26,34,0,0.000000,1,44.0,2,17.000000,45488,0,"$219,378",...,"$22,090",17,0,0,$0,0,0,0,12.0,0
27,35,0,0.000000,0,35.0,0,8.000000,72193,0,$0,...,"$12,220",6,5,0,$0,0,0,3,12.0,0
28,36,0,0.000000,0,40.0,2,0.000000,NaN,0,"$98,777",...,"$14,130",6,5,0,"$38,127",2,1,4,12.0,1
29,38,0,0.000000,0,49.0,0,5.000000,49244,0,"$163,444",...,"$15,880",1,0,0,$0,0,0,1,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8131,10260,0,0.000000,0,56.0,0,13.000000,52130,0,"$176,831",...,"$12,310",3,5,0,"$10,494",2,0,3,4.0,0
8132,10261,1,3179.000000,0,47.0,0,10.499286,112264,0,$0,...,"$24,020",1,1,1,"$22,762",1,1,5,20.0,0
8133,10263,1,3106.000000,0,47.0,0,13.000000,282198,0,"$649,247",...,"$34,420",11,1,1,$0,0,1,2,16.0,0
8134,10265,1,471.115458,0,43.0,0,10.499286,0,0,"$55,203",...,"$24,030",9,0,0,"$3,035",4,0,0,14.0,0
8135,10267,0,0.000000,1,45.0,1,14.000000,1956,1,$0,...,"$8,350",1,5,0,$0,0,0,0,1.0,1
8136,10269,0,0.000000,0,32.0,2,14.000000,NaN,0,"$219,966",...,"$19,680",10,4,0,$0,0,0,1,9.0,1
8137,10270,1,3135.000000,0,46.0,0,10.000000,68360,0,"$237,457",...,"$12,940",1,0,0,"$6,560",3,0,7,11.0,0
8138,10273,0,0.000000,1,46.0,0,10.000000,84667,0,"$236,725",...,"$35,050",1,1,0,$0,0,0,0,7.0,0
8139,10274,0,0.000000,0,48.0,0,12.000000,66613,0,"$209,239",...,"$16,340",6,5,0,$0,0,0,0,5.0,1
8140,10275,0,0.000000,0,56.0,0,11.000000,12917,0,NaN,...,"$2,790",4,5,0,$0,0,0,0,12.0,0
8141,10278,0,0.000000,0,35.0,0,7.000000,64890,0,$0,...,"$7,990",8,5,0,$0,0,0,1,12.0,0
8142,10280,0,0.000000,0,49.0,0,12.000000,60049,0,"$227,054",...,"$6,200",1,5,0,$0,0,0,0,1.0,1
8143,10282,0,0.000000,0,42.0,0,12.000000,80078,0,"$266,403",...,"$20,640",1,0,0,$0,0,0,2,16.0,0
8144,10283,0,0.000000,0,36.0,2,13.000000,131335,1,"$352,524",...,"$28,490",1,3,0,$0,0,0,0,4.0,1
8145,10284,0,0.000000,0,38.0,3,8.000000,83458,1,"$232,182",...,"$28,260",6,3,0,"$9,298",2,0,3,9.0,0
8146,10286,1,1815.205097,0,41.0,0,12.000000,92185,0,"$289,370",...,"$1,500",11,0,1,$0,0,0,0,10.0,0
8147,10287,0,0.000000,0,60.0,0,12.000000,19796,0,"$153,061",...,"$21,690",1,3,0,"$2,800",2,0,4,1.0,0
8148,10288,1,2967.000000,0,45.0,0,11.000000,52966,0,$0,...,"$11,300",6,2,1,"$16,239",2,1,5,1.0,0
8149,10289,0,0.000000,0,54.0,0,11.000000,69111,0,"$291,969",...,"$16,510",1,4,1,"$5,038",1,0,3,1.0,0
8150,10290,0,0.000000,0,54.0,0,13.000000,62060,0,"$244,889",...,"$1,500",6,0,0,$0,0,0,3,1.0,0
8151,10291,0,0.000000,0,54.0,0,13.000000,81818,0,"$272,725",...,"$19,660",1,4,0,"$24,690",1,1,6,4.0,0
8152,10292,0,0.000000,1,46.0,0,12.000000,45018,0,$0,...,"$15,060",4,0,0,"$33,026",3,0,0,1.0,1
8153,10293,0,0.000000,0,48.0,0,10.000000,111305,0,$0,...,"$17,430",13,5,0,$0,0,0,4,18.0,0
8154,10295,0,0.000000,1,38.0,4,16.000000,12717,0,$0,...,"$24,740",1,2,0,"$9,245",3,0,3,15.0,0
8155,10296,0,0.000000,0,41.0,0,7.000000,6256,0,$0,...,"$5,600",1,2,0,$0,0,0,0,7.0,1
8156,10297,0,0.000000,0,35.0,0,11.000000,43112,0,$0,...,"$27,330",10,1,1,$0,0,0,0,8.0,1
8157,10298,0,0.000000,1,45.0,2,9.000000,164669,0,"$386,273",...,"$13,270",15,0,0,$0,0,0,2,17.0,0
8158,10299,0,0.000000,0,46.0,0,9.000000,107204,0,"$332,591",...,"$24,490",6,1,0,$0,0,0,0,1.0,0
8159,10301,0,0.000000,0,50.0,0,7.000000,43445,0,"$149,248",...,"$22,550",6,0,0,$0,0,0,0,11.0,0
8160,10302,0,0.000000,0,52.0,0,11.000000,53235,0,"$197,017",...,"$19,400",6,0,0,$0,0,0,0,9.0,1

In [94]:
data.INCOME = data.INCOME.astype(float)

In [90]:
data.mean()

INDEX           5151.867663
TARGET_FLAG        0.263816
TARGET_AMT      1504.324648
KIDSDRIV           0.171057
AGE               44.790313
HOMEKIDS           0.721235
YOJ               10.499286
INCOME         61898.094609
PARENT1            0.131969
TRAVTIME          33.485725
TIF                5.351305
CAR_TYPE           2.529714
RED_CAR            0.291386
CLM_FREQ           0.798554
REVOKED            0.122534
MVR_PTS            1.695503
CAR_AGE            8.328323
URBANICITY         0.204509
dtype: float64

In [91]:
str(data.INCOME)

'0        67349.0\n1        91449.0\n2        16039.0\n3            NaN\n4       114986.0\n5       125301.0\n6        18755.0\n7       107961.0\n8        62978.0\n9       106952.0\n10       77100.0\n11       52642.0\n12       59162.0\n13      130795.0\n14           0.0\n15       51884.0\n16       59945.0\n17       34019.0\n18       18903.0\n19       44077.0\n20       37214.0\n21       96274.0\n22       46281.0\n23           0.0\n24       79606.0\n25       31275.0\n26       45488.0\n27       72193.0\n28           NaN\n29       49244.0\n          ...   \n8131     52130.0\n8132    112264.0\n8133    282198.0\n8134         0.0\n8135      1956.0\n8136         NaN\n8137     68360.0\n8138     84667.0\n8139     66613.0\n8140     12917.0\n8141     64890.0\n8142     60049.0\n8143     80078.0\n8144    131335.0\n8145     83458.0\n8146     92185.0\n8147     19796.0\n8148     52966.0\n8149     69111.0\n8150     62060.0\n8151     81818.0\n8152     45018.0\n8153    111305.0\n8154     12717.0\n8155      6256.0\n8156     43112.0\n8157    164669.0\n8158    107204.0\n8159     43445.0\n8160     53235.0\nName: INCOME, Length: 8161, dtype: float64'

In [95]:
data.INCOME

0        67349.0
1        91449.0
2        16039.0
3            NaN
4       114986.0
5       125301.0
6        18755.0
7       107961.0
8        62978.0
9       106952.0
10       77100.0
11       52642.0
12       59162.0
13      130795.0
14           0.0
15       51884.0
16       59945.0
17       34019.0
18       18903.0
19       44077.0
20       37214.0
21       96274.0
22       46281.0
23           0.0
24       79606.0
25       31275.0
26       45488.0
27       72193.0
28           NaN
29       49244.0
          ...
8131     52130.0
8132    112264.0
8133    282198.0
8134         0.0
8135      1956.0
8136         NaN
8137     68360.0
8138     84667.0
8139     66613.0
8140     12917.0
8141     64890.0
8142     60049.0
8143     80078.0
8144    131335.0
8145     83458.0
8146     92185.0
8147     19796.0
8148     52966.0
8149     69111.0
8150     62060.0
8151     81818.0
8152     45018.0
8153    111305.0
8154     12717.0
8155      6256.0
8156     43112.0
8157    164669.0
8158    107204.0
8159     43445.0
8160     53235.0
Name: INCOME, Length: 8161, dtype: float64

In [96]:
data = data.fillna(data.mean())

In [97]:
data

,INDEX,TARGET_FLAG,TARGET_AMT,KIDSDRIV,AGE,HOMEKIDS,YOJ,INCOME,PARENT1,HOME_VAL,...,BLUEBOOK,TIF,CAR_TYPE,RED_CAR,OLDCLAIM,CLM_FREQ,REVOKED,MVR_PTS,CAR_AGE,URBANICITY
0,1,0,0.000000,0,60.0,0,11.000000,67349.000000,0,$0,...,"$14,230",11,0,1,"$4,461",2,0,3,18.0,0
1,2,0,0.000000,0,43.0,0,11.000000,91449.000000,0,"$257,252",...,"$14,940",1,0,1,$0,0,0,0,1.0,0
2,4,0,0.000000,0,35.0,1,10.000000,16039.000000,0,"$124,191",...,"$4,010",4,5,0,"$38,690",2,0,3,10.0,0
3,5,0,0.000000,0,51.0,0,14.000000,61898.094609,0,"$306,251",...,"$15,440",7,0,1,$0,0,0,0,6.0,0
4,6,0,0.000000,0,50.0,0,10.499286,114986.000000,0,"$243,925",...,"$18,000",1,5,0,"$19,217",2,1,3,17.0,0
5,7,1,2946.000000,0,34.0,1,12.000000,125301.000000,1,$0,...,"$17,430",1,3,0,$0,0,0,0,7.0,0
6,8,0,0.000000,0,54.0,0,10.499286,18755.000000,0,NaN,...,"$8,780",1,5,0,$0,0,0,0,1.0,0
7,11,1,4021.000000,1,37.0,2,10.499286,107961.000000,0,"$333,680",...,"$16,970",1,4,1,"$2,374",1,1,10,7.0,0
8,12,1,2501.000000,0,34.0,0,10.000000,62978.000000,0,$0,...,"$11,200",1,5,0,$0,0,0,0,1.0,0
9,13,0,0.000000,0,50.0,0,7.000000,106952.000000,0,$0,...,"$18,510",7,4,0,$0,0,0,1,17.0,1
10,14,1,6077.000000,0,53.0,0,14.000000,77100.000000,0,$0,...,"$18,300",1,3,0,$0,0,0,0,11.0,0
11,15,0,0.000000,0,43.0,0,5.000000,52642.000000,0,"$209,970",...,"$22,420",7,0,0,$0,0,0,0,1.0,1
12,16,0,0.000000,0,55.0,0,11.000000,59162.000000,0,"$180,232",...,"$17,600",7,4,1,"$5,028",2,1,3,9.0,0
13,17,1,1267.000000,0,53.0,0,11.000000,130795.000000,0,$0,...,"$28,340",6,1,1,$0,0,0,3,10.0,0
14,19,1,2920.167320,0,45.0,0,0.000000,0.000000,0,"$106,859",...,"$6,000",1,5,0,$0,0,0,3,5.0,0
15,20,0,0.000000,0,39.0,3,12.000000,51884.000000,1,"$180,951",...,"$10,590",6,5,0,$0,0,0,0,13.0,1
16,22,0,0.000000,0,42.0,0,11.000000,59945.000000,0,"$192,207",...,"$14,190",6,0,0,$0,0,0,0,16.0,0
17,23,0,0.000000,0,34.0,3,13.000000,34019.000000,0,"$91,875",...,"$8,300",7,5,0,$0,0,0,0,20.0,0
18,24,0,0.000000,0,31.0,2,12.000000,18903.000000,0,"$93,797",...,"$17,330",4,0,0,$0,0,0,0,7.0,0
19,25,1,6857.000000,0,28.0,1,13.000000,44077.000000,0,"$170,598",...,"$8,710",6,5,0,"$8,935",2,0,0,1.0,0
20,26,1,3627.000000,0,43.0,0,13.000000,37214.000000,0,NaN,...,"$26,560",1,1,1,$0,0,0,3,1.0,0
21,27,0,0.000000,0,48.0,0,14.000000,96274.000000,0,"$282,904",...,"$11,130",6,5,0,"$8,250",1,0,5,14.0,0
22,28,0,0.000000,0,47.0,0,11.000000,46281.000000,0,$0,...,"$19,700",10,0,0,$0,0,0,1,5.0,0
23,29,0,0.000000,2,44.0,2,0.000000,0.000000,0,"$82,344",...,"$5,900",6,5,0,"$3,338",3,0,0,11.0,0
24,32,0,0.000000,0,33.0,1,13.000000,79606.000000,0,"$225,962",...,"$16,830",9,5,0,$0,0,0,2,15.0,1
25,33,1,4486.000000,0,32.0,1,9.000000,31275.000000,0,"$118,160",...,"$10,030",1,5,0,$0,0,0,0,1.0,0
26,34,0,0.000000,1,44.0,2,17.000000,45488.000000,0,"$219,378",...,"$22,090",17,0,0,$0,0,0,0,12.0,0
27,35,0,0.000000,0,35.0,0,8.000000,72193.000000,0,$0,...,"$12,220",6,5,0,$0,0,0,3,12.0,0
28,36,0,0.000000,0,40.0,2,0.000000,61898.094609,0,"$98,777",...,"$14,130",6,5,0,"$38,127",2,1,4,12.0,1
29,38,0,0.000000,0,49.0,0,5.000000,49244.000000,0,"$163,444",...,"$15,880",1,0,0,$0,0,0,1,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8131,10260,0,0.000000,0,56.0,0,13.000000,52130.000000,0,"$176,831",...,"$12,310",3,5,0,"$10,494",2,0,3,4.0,0
8132,10261,1,3179.000000,0,47.0,0,10.499286,112264.000000,0,$0,...,"$24,020",1,1,1,"$22,762",1,1,5,20.0,0
8133,10263,1,3106.000000,0,47.0,0,13.000000,282198.000000,0,"$649,247",...,"$34,420",11,1,1,$0,0,1,2,16.0,0
8134,10265,1,471.115458,0,43.0,0,10.499286,0.000000,0,"$55,203",...,"$24,030",9,0,0,"$3,035",4,0,0,14.0,0
8135,10267,0,0.000000,1,45.0,1,14.000000,1956.000000,1,$0,...,"$8,350",1,5,0,$0,0,0,0,1.0,1
8136,10269,0,0.000000,0,32.0,2,14.000000,61898.094609,0,"$219,966",...,"$19,680",10,4,0,$0,0,0,1,9.0,1
8137,10270,1,3135.000000,0,46.0,0,10.000000,68360.000000,0,"$237,457",...,"$12,940",1,0,0,"$6,560",3,0,7,11.0,0
8138,10273,0,0.000000,1,46.0,0,10.000000,84667.000000,0,"$236,725",...,"$35,050",1,1,0,$0,0,0,0,7.0,0
8139,10274,0,0.000000,0,48.0,0,12.000000,66613.000000,0,"$209,239",...,"$16,340",6,5,0,$0,0,0,0,5.0,1
8140,10275,0,0.000000,0,56.0,0,11.000000,12917.000000,0,NaN,...,"$2,790",4,5,0,$0,0,0,0,12.0,0
8141,10278,0,0.000000,0,35.0,0,7.000000,64890.000000,0,$0,...,"$7,990",8,5,0,$0,0,0,1,12.0,0
8142,10280,0,0.000000,0,49.0,0,12.000000,60049.000000,0,"$227,054",...,"$6,200",1,5,0,$0,0,0,0,1.0,1
8143,10282,0,0.000000,0,42.0,0,12.000000,80078.000000,0,"$266,403",...,"$20,640",1,0,0,$0,0,0,2,16.0,0
8144,10283,0,0.000000,0,36.0,2,13.000000,131335.000000,1,"$352,524",...,"$28,490",1,3,0,$0,0,0,0,4.0,1
8145,10284,0,0.000000,0,38.0,3,8.000000,83458.000000,1,"$232,182",...,"$28,260",6,3,0,"$9,298",2,0,3,9.0,0
8146,10286,1,1815.205097,0,41.0,0,12.000000,92185.000000,0,"$289,370",...,"$1,500",11,0,1,$0,0,0,0,10.0,0
8147,10287,0,0.000000,0,60.0,0,12.000000,19796.000000,0,"$153,061",...,"$21,690",1,3,0,"$2,800",2,0,4,1.0,0
8148,10288,1,2967.000000,0,45.0,0,11.000000,52966.000000,0,$0,...,"$11,300",6,2,1,"$16,239",2,1,5,1.0,0
8149,10289,0,0.000000,0,54.0,0,11.000000,69111.000000,0,"$291,969",...,"$16,510",1,4,1,"$5,038",1,0,3,1.0,0
8150,10290,0,0.000000,0,54.0,0,13.000000,62060.000000,0,"$244,889",...,"$1,500",6,0,0,$0,0,0,3,1.0,0
8151,10291,0,0.000000,0,54.0,0,13.000000,81818.000000,0,"$272,725",...,"$19,660",1,4,0,"$24,690",1,1,6,4.0,0
8152,10292,0,0.000000,1,46.0,0,12.000000,45018.000000,0,$0,...,"$15,060",4,0,0,"$33,026",3,0,0,1.0,1
8153,10293,0,0.000000,0,48.0,0,10.000000,111305.000000,0,$0,...,"$17,430",13,5,0,$0,0,0,4,18.0,0
8154,10295,0,0.000000,1,38.0,4,16.000000,12717.000000,0,$0,...,"$24,740",1,2,0,"$9,245",3,0,3,15.0,0
8155,10296,0,0.000000,0,41.0,0,7.000000,6256.000000,0,$0,...,"$5,600",1,2,0,$0,0,0,0,7.0,1
8156,10297,0,0.000000,0,35.0,0,11.000000,43112.000000,0,$0,...,"$27,330",10,1,1,$0,0,0,0,8.0,1
8157,10298,0,0.000000,1,45.0,2,9.000000,164669.000000,0,"$386,273",...,"$13,270",15,0,0,$0,0,0,2,17.0,0
8158,10299,0,0.000000,0,46.0,0,9.000000,107204.000000,0,"$332,591",...,"$24,490",6,1,0,$0,0,0,0,1.0,0
8159,10301,0,0.000000,0,50.0,0,7.000000,43445.000000,0,"$149,248",...,"$22,550",6,0,0,$0,0,0,0,11.0,0
8160,10302,0,0.000000,0,52.0,0,11.000000,53235.000000,0,"$197,017",...,"$19,400",6,0,0,$0,0,0,0,9.0,1