In [46]:
import pandas as pd
import numpy as np
import datetime
import time

In [182]:
data = pd.read_csv("/home/koushik/Downloads/FinalDataSet_V4.5.csv" , parse_dates=['VALUATION'])
data['sno'] = data.index

In [221]:
data

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
0,10001,2015-01-31,ACTIVE,8299.0,01-01-2012,1900,36.993840,36,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,0,0
1,10001,2015-02-28,ACTIVE,8299.0,01-01-2012,1900,37.913758,37,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,1,0
2,10001,2015-03-31,ACTIVE,8299.0,01-01-2012,1900,38.932238,38,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,2,0
3,10001,2015-04-30,ACTIVE,8299.0,01-01-2012,1900,39.917864,39,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,0
4,10001,2015-05-31,ACTIVE,8299.0,01-01-2012,1900,40.936345,40,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,4,0
5,10001,2015-06-30,ACTIVE,8299.0,01-01-2012,1900,41.921971,41,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,5,0
6,10001,2015-07-31,ACTIVE,8299.0,01-01-2012,1900,43.058339,42,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,6,0
7,10001,2015-08-31,ACTIVE,8299.0,01-01-2012,1900,43.958932,43,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,7,0
8,10001,2015-09-30,ACTIVE,8299.0,01-01-2012,1900,44.944559,44,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,8,0
9,10001,2015-10-31,ACTIVE,8299.0,01-01-2012,1900,45.963039,45,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,9,0
10,10001,2015-11-30,ACTIVE,8299.0,01-01-2012,1900,46.948665,46,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,10,0
11,10001,2015-12-31,ACTIVE,8299.0,01-01-2012,1900,47.967146,47,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,11,0
12,10001,2016-01-31,ACTIVE,8299.0,01-01-2012,1900,48.985626,48,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,12,0
13,10001,2016-02-29,ACTIVE,8299.0,01-01-2012,1900,49.938398,49,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,13,0
14,10001,2016-03-31,ACTIVE,8299.0,01-01-2012,1900,50.956879,50,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,14,0
15,10001,2016-04-30,ACTIVE,8299.0,01-01-2012,1900,51.942505,51,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,15,0
16,10001,2016-05-31,ACTIVE,8299.0,01-01-2012,1900,52.960986,52,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,16,0
17,10001,2016-06-30,Active,8299.0,01-01-2012,1900,52.961000,53,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,17,0
18,10001,2016-07-31,ACTIVE,8299.0,01-01-2012,1900,54.965092,54,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,18,0
19,10001,2016-08-31,ACTIVE,8299.0,01-01-2012,1900,55.983573,55,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,19,0
20,10001,2016-09-30,ACTIVE,8299.0,01-01-2012,1900,56.969199,56,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,20,0
21,10001,2016-10-31,ACTIVE,8299.0,01-01-2012,1900,57.987680,57,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,21,0
22,10001,2016-11-30,ACTIVE,8299.0,01-01-2012,1900,58.973306,58,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,22,0
23,10001,2016-12-31,ACTIVE,8299.0,01-01-2012,1900,59.991786,59,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,23,0
24,10001,2017-01-31,ACTIVE,8299.0,01-01-2012,1900,61.010267,60,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,24,0
25,10001,2017-02-28,ACTIVE,8299.0,01-01-2012,1900,61.930185,61,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,25,0
26,10003,2015-01-31,ACTIVE,5211.0,01-01-2012,200,36.993840,36,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,26,0
27,10003,2015-02-28,ACTIVE,5211.0,01-01-2012,200,37.913758,37,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,27,0
28,10003,2015-03-31,ACTIVE,5211.0,01-01-2012,200,38.932238,38,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,28,0
29,10003,2015-04-30,ACTIVE,5211.0,01-01-2012,200,39.917864,39,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182989,A1,2016-06-30,Active,NaN,01-01-2010,3800,76.944600,77,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182989,0
182990,A1,2016-07-31,ACTIVE,NaN,01-01-2010,3800,78.948665,78,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182990,0
182991,A1,2016-08-31,ACTIVE,NaN,01-01-2010,3800,79.967146,79,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182991,0
182992,A1,2016-09-30,ACTIVE,NaN,01-01-2010,3800,80.952772,80,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182992,0
182993,A1,2016-10-31,ACTIVE,NaN,01-01-2010,3800,81.971253,81,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182993,0
182994,A1,2016-11-30,ACTIVE,NaN,01-01-2010,3800,82.956879,82,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182994,0
182995,A1,2016-12-31,ACTIVE,NaN,01-01-2010,3800,83.975359,83,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182995,0
182996,A1,2017-01-31,ACTIVE,NaN,01-01-2010,3800,84.993840,84,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182996,0
182997,A1,2017-02-28,ACTIVE,NaN,01-01-2010,3800,85.913758,85,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182997,0
182998,A2,2015-01-31,ACTIVE,NaN,01-03-2010,200,59.039014,58,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182998,0
182999,A2,2015-02-28,ACTIVE,NaN,01-03-2010,200,59.958932,59,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182999,0
183000,A2,2015-03-31,ACTIVE,NaN,01-03-2010,200,60.977413,60,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183000,0
183001,A2,2015-04-30,ACTIVE,NaN,01-03-2010,200,61.963039,61,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183001,0
183002,A2,2015-05-31,ACTIVE,NaN,01-03-2010,200,62.981520,62,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183002,0
183003,A2,2015-06-30,ACTIVE,NaN,01-03-2010,200,63.967146,63,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183003,0
183004,A2,2015-07-31,ACTIVE,NaN,01-03-2010,200,65.164036,64,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183004,0
183005,A2,2015-08-31,ACTIVE,NaN,01-03-2010,200,66.004107,65,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183005,0
183006,A2,2015-09-30,ACTIVE,NaN,01-03-2010,200,66.989733,66,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183006,0
183007,A2,2015-10-31,ACTIVE,NaN,01-03-2010,200,68.008214,67,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183007,0
183008,A2,2015-11-30,ACTIVE,NaN,01-03-2010,200,68.993840,68,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183008,0
183009,A2,2015-12-31,ACTIVE,NaN,01-03-2010,200,70.012320,69,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183009,0
183010,A2,2016-01-31,ACTIVE,NaN,01-03-2010,200,71.030801,70,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183010,0
183011,A2,2016-02-29,ACTIVE,NaN,01-03-2010,200,71.983573,71,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183011,0
183012,A2,2016-03-31,ACTIVE,NaN,01-03-2010,200,73.002053,72,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183012,0
183013,A2,2016-04-30,ACTIVE,NaN,01-03-2010,200,73.987680,73,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183013,0
183014,A2,2016-05-31,ACTIVE,NaN,01-03-2010,200,75.006160,74,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183014,0
183015,A2,2016-06-30,Active,NaN,01-03-2010,200,75.006200,75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183015,0
183016,A2,2016-07-31,ACTIVE,NaN,01-03-2010,200,77.010267,76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183016,0
183017,A2,2016-08-31,ACTIVE,NaN,01-03-2010,200,78.028747,77,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183017,0
183018,A2,2016-09-30,LAPSED,NaN,01-03-2010,200,79.014374,78,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183018,0

In [185]:
data.iloc[0].STATUS

'ACTIVE'

In [210]:
type(data.VALUATION[1])

pandas._libs.tslib.Timestamp

In [188]:
start = time.time()
for i in range(0,100):
    j=0
    for i in range(1,4):
        if data.iloc[i].VALUATION > end_date:
            break 
        if data.iloc[i+j].GRPNUM != data.iloc[i+j]:

SyntaxError: invalid syntax (<ipython-input-188-030e150fa264>, line 7)

In [189]:
data

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
0,10001,2015-01-31,ACTIVE,8299.0,01-01-2012,1900,36.993840,36,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,0,0
1,10001,2015-02-28,ACTIVE,8299.0,01-01-2012,1900,37.913758,37,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,1,0
2,10001,2015-03-31,ACTIVE,8299.0,01-01-2012,1900,38.932238,38,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,2,0
3,10001,2015-04-30,ACTIVE,8299.0,01-01-2012,1900,39.917864,39,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,0
4,10001,2015-05-31,ACTIVE,8299.0,01-01-2012,1900,40.936345,40,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,4,0
5,10001,2015-06-30,ACTIVE,8299.0,01-01-2012,1900,41.921971,41,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,5,0
6,10001,2015-07-31,ACTIVE,8299.0,01-01-2012,1900,43.058339,42,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,6,0
7,10001,2015-08-31,ACTIVE,8299.0,01-01-2012,1900,43.958932,43,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,7,0
8,10001,2015-09-30,ACTIVE,8299.0,01-01-2012,1900,44.944559,44,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,8,0
9,10001,2015-10-31,ACTIVE,8299.0,01-01-2012,1900,45.963039,45,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,9,0
10,10001,2015-11-30,ACTIVE,8299.0,01-01-2012,1900,46.948665,46,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,10,0
11,10001,2015-12-31,ACTIVE,8299.0,01-01-2012,1900,47.967146,47,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,11,0
12,10001,2016-01-31,ACTIVE,8299.0,01-01-2012,1900,48.985626,48,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,12,0
13,10001,2016-02-29,ACTIVE,8299.0,01-01-2012,1900,49.938398,49,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,13,0
14,10001,2016-03-31,ACTIVE,8299.0,01-01-2012,1900,50.956879,50,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,14,0
15,10001,2016-04-30,ACTIVE,8299.0,01-01-2012,1900,51.942505,51,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,15,0
16,10001,2016-05-31,ACTIVE,8299.0,01-01-2012,1900,52.960986,52,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,16,0
17,10001,2016-06-30,Active,8299.0,01-01-2012,1900,52.961000,53,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,17,0
18,10001,2016-07-31,ACTIVE,8299.0,01-01-2012,1900,54.965092,54,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,18,0
19,10001,2016-08-31,ACTIVE,8299.0,01-01-2012,1900,55.983573,55,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,19,0
20,10001,2016-09-30,ACTIVE,8299.0,01-01-2012,1900,56.969199,56,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,20,0
21,10001,2016-10-31,ACTIVE,8299.0,01-01-2012,1900,57.987680,57,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,21,0
22,10001,2016-11-30,ACTIVE,8299.0,01-01-2012,1900,58.973306,58,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,22,0
23,10001,2016-12-31,ACTIVE,8299.0,01-01-2012,1900,59.991786,59,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,23,0
24,10001,2017-01-31,ACTIVE,8299.0,01-01-2012,1900,61.010267,60,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,24,0
25,10001,2017-02-28,ACTIVE,8299.0,01-01-2012,1900,61.930185,61,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,25,0
26,10003,2015-01-31,ACTIVE,5211.0,01-01-2012,200,36.993840,36,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,26,0
27,10003,2015-02-28,ACTIVE,5211.0,01-01-2012,200,37.913758,37,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,27,0
28,10003,2015-03-31,ACTIVE,5211.0,01-01-2012,200,38.932238,38,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,28,0
29,10003,2015-04-30,ACTIVE,5211.0,01-01-2012,200,39.917864,39,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182989,A1,2016-06-30,Active,NaN,01-01-2010,3800,76.944600,77,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182989,0
182990,A1,2016-07-31,ACTIVE,NaN,01-01-2010,3800,78.948665,78,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182990,0
182991,A1,2016-08-31,ACTIVE,NaN,01-01-2010,3800,79.967146,79,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182991,0
182992,A1,2016-09-30,ACTIVE,NaN,01-01-2010,3800,80.952772,80,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182992,0
182993,A1,2016-10-31,ACTIVE,NaN,01-01-2010,3800,81.971253,81,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182993,0
182994,A1,2016-11-30,ACTIVE,NaN,01-01-2010,3800,82.956879,82,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182994,0
182995,A1,2016-12-31,ACTIVE,NaN,01-01-2010,3800,83.975359,83,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182995,0
182996,A1,2017-01-31,ACTIVE,NaN,01-01-2010,3800,84.993840,84,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182996,0
182997,A1,2017-02-28,ACTIVE,NaN,01-01-2010,3800,85.913758,85,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182997,0
182998,A2,2015-01-31,ACTIVE,NaN,01-03-2010,200,59.039014,58,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182998,0
182999,A2,2015-02-28,ACTIVE,NaN,01-03-2010,200,59.958932,59,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182999,0
183000,A2,2015-03-31,ACTIVE,NaN,01-03-2010,200,60.977413,60,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183000,0
183001,A2,2015-04-30,ACTIVE,NaN,01-03-2010,200,61.963039,61,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183001,0
183002,A2,2015-05-31,ACTIVE,NaN,01-03-2010,200,62.981520,62,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183002,0
183003,A2,2015-06-30,ACTIVE,NaN,01-03-2010,200,63.967146,63,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183003,0
183004,A2,2015-07-31,ACTIVE,NaN,01-03-2010,200,65.164036,64,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183004,0
183005,A2,2015-08-31,ACTIVE,NaN,01-03-2010,200,66.004107,65,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183005,0
183006,A2,2015-09-30,ACTIVE,NaN,01-03-2010,200,66.989733,66,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183006,0
183007,A2,2015-10-31,ACTIVE,NaN,01-03-2010,200,68.008214,67,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183007,0
183008,A2,2015-11-30,ACTIVE,NaN,01-03-2010,200,68.993840,68,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183008,0
183009,A2,2015-12-31,ACTIVE,NaN,01-03-2010,200,70.012320,69,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183009,0
183010,A2,2016-01-31,ACTIVE,NaN,01-03-2010,200,71.030801,70,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183010,0
183011,A2,2016-02-29,ACTIVE,NaN,01-03-2010,200,71.983573,71,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183011,0
183012,A2,2016-03-31,ACTIVE,NaN,01-03-2010,200,73.002053,72,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183012,0
183013,A2,2016-04-30,ACTIVE,NaN,01-03-2010,200,73.987680,73,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183013,0
183014,A2,2016-05-31,ACTIVE,NaN,01-03-2010,200,75.006160,74,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183014,0
183015,A2,2016-06-30,Active,NaN,01-03-2010,200,75.006200,75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183015,0
183016,A2,2016-07-31,ACTIVE,NaN,01-03-2010,200,77.010267,76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183016,0
183017,A2,2016-08-31,ACTIVE,NaN,01-03-2010,200,78.028747,77,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183017,0
183018,A2,2016-09-30,LAPSED,NaN,01-03-2010,200,79.014374,78,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183018,0

In [190]:
type(data.VALUATION[1])

pandas._libs.tslib.Timestamp

In [253]:
data[data.VALUATION > date]

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
24,10001,2017-01-31,ACTIVE,8299.0,01-01-2012,1900,61.010267,60,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,24,7
25,10001,2017-02-28,ACTIVE,8299.0,01-01-2012,1900,61.930185,61,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,25,7
50,10003,2017-01-31,ACTIVE,5211.0,01-01-2012,200,61.010267,60,NaN,NaN,...,30-11-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,50,7
51,10003,2017-02-28,ACTIVE,5211.0,01-01-2012,200,61.930185,61,NaN,NaN,...,30-11-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,51,7
76,10006,2017-01-31,ACTIVE,8211.0,01-11-2011,3500,63.014374,62,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,76,7
77,10006,2017-02-28,ACTIVE,8211.0,01-11-2011,3500,63.934292,63,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,77,7
102,10007,2017-01-31,ACTIVE,8051.0,01-11-2011,215,63.014374,62,NaN,NaN,...,01-12-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,102,7
103,10007,2017-02-28,ACTIVE,8051.0,01-11-2011,215,63.934292,63,NaN,NaN,...,01-12-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,103,7
128,10008,2017-01-31,ACTIVE,8099.0,01-10-2011,273,64.032854,63,NaN,NaN,...,30-09-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,No,128,7
129,10008,2017-02-28,ACTIVE,8099.0,01-10-2011,273,64.952772,64,NaN,NaN,...,30-09-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,No,129,7
154,10009,2017-01-31,ACTIVE,5511.0,01-10-2011,180,64.032854,63,NaN,NaN,...,25-03-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,154,7
155,10009,2017-02-28,ACTIVE,5511.0,01-10-2011,180,64.952772,64,NaN,NaN,...,25-03-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,155,7
180,10011,2017-01-31,ACTIVE,8299.0,01-11-2011,132,63.014374,62,NaN,NaN,...,10-10-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,180,7
181,10011,2017-02-28,ACTIVE,8299.0,01-11-2011,132,63.934292,63,NaN,NaN,...,10-10-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,181,7
206,10012,2017-01-31,ACTIVE,8399.0,01-10-2011,151,64.032854,63,1.0,0.0,...,15-08-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,206,7
207,10012,2017-02-28,ACTIVE,8399.0,01-10-2011,151,64.952772,64,1.0,0.0,...,15-08-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,207,7
236,10015,2017-01-31,ACTIVE,8062.0,01-10-2011,165,64.032854,63,12.0,4.0,...,10-12-2016,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,236,7
237,10015,2017-02-28,ACTIVE,8062.0,01-10-2011,165,64.952772,64,14.0,4.0,...,10-12-2016,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,237,7
262,10016,2017-01-31,ACTIVE,8734.0,01-10-2011,360,64.032854,63,NaN,NaN,...,02-12-2016,Yes,NaN,Broker,Never Enrolled,NaN,Non-MGA,Yes,262,7
263,10016,2017-02-28,ACTIVE,8734.0,01-10-2011,360,64.952772,64,NaN,NaN,...,02-12-2016,Yes,NaN,Broker,Never Enrolled,NaN,Non-MGA,Yes,263,7
288,10017,2017-01-31,ACTIVE,8211.0,01-10-2011,625,64.032854,63,1.0,0.0,...,02-12-2016,No,NaN,Field Force,No Apps Taken,NaN,Non-MGA,Yes,288,7
289,10017,2017-02-28,ACTIVE,8211.0,01-10-2011,625,64.952772,64,1.0,0.0,...,02-12-2016,No,NaN,Field Force,No Apps Taken,NaN,Non-MGA,Yes,289,7
324,10019,2017-01-31,ACTIVE,8299.0,01-10-2011,440,64.032854,63,NaN,NaN,...,22-12-2016,No,NaN,Field Force,No Apps Taken,NaN,Non-MGA,No,324,0
325,10019,2017-02-28,ACTIVE,8299.0,01-10-2011,440,64.952772,64,NaN,NaN,...,22-12-2016,No,NaN,Field Force,No Apps Taken,NaN,Non-MGA,No,325,0
350,10020,2017-01-31,ACTIVE,7011.0,01-10-2011,200,64.032854,63,NaN,NaN,...,26-08-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,350,0
351,10020,2017-02-28,ACTIVE,7011.0,01-10-2011,200,64.952772,64,NaN,NaN,...,26-08-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,351,0
376,10021,2017-01-31,ACTIVE,9199.0,01-10-2011,100,64.032854,63,NaN,NaN,...,04-12-2015,No,NaN,Field Force,Never Enrolled,NaN,Non-MGA,No,376,0
377,10021,2017-02-28,ACTIVE,9199.0,01-10-2011,100,64.952772,64,NaN,NaN,...,04-12-2015,No,NaN,Field Force,Never Enrolled,NaN,Non-MGA,No,377,0
402,10025,2017-01-31,ACTIVE,5812.0,01-11-2011,145,63.014374,62,NaN,NaN,...,30-09-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,402,0
403,10025,2017-02-28,ACTIVE,5812.0,01-11-2011,145,63.934292,63,NaN,NaN,...,30-09-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,403,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182598,9973,2017-01-31,ACTIVE,9191.0,01-06-2011,100,68.041068,67,NaN,NaN,...,30-04-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182598,0
182599,9973,2017-02-28,ACTIVE,9191.0,01-06-2011,100,68.960986,68,NaN,NaN,...,30-04-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182599,0
182624,9974,2017-01-31,ACTIVE,5045.0,01-06-2011,13989,68.041068,67,57.0,51.0,...,28-11-2016,No,NaN,Broker,In Force,Y,Non-MGA,Yes,182624,0
182625,9974,2017-02-28,ACTIVE,5045.0,01-06-2011,13989,68.960986,68,57.0,51.0,...,28-11-2016,No,NaN,Broker,In Force,Y,Non-MGA,Yes,182625,0
182650,9975,2017-01-31,ACTIVE,8099.0,01-07-2011,10400,67.055441,66,192.0,192.0,...,20-05-2016,No,NaN,Broker,In Force,Y,Non-MGA,Yes,182650,0
182651,9975,2017-02-28,ACTIVE,8099.0,01-07-2011,10400,67.975359,67,192.0,192.0,...,20-05-2016,No,NaN,Broker,In Force,Y,Non-MGA,Yes,182651,0
182676,9977,2017-01-31,ACTIVE,3714.0,01-05-2011,119,69.059548,68,NaN,NaN,...,13-02-2016,No,NaN,Field Force,Never Enrolled,NaN,Non-MGA,Yes,182676,0
182677,9977,2017-02-28,ACTIVE,3714.0,01-05-2011,119,69.979466,69,NaN,NaN,...,13-02-2016,No,NaN,Field Force,Never Enrolled,NaN,Non-MGA,Yes,182677,0
182702,9978,2017-01-31,ACTIVE,5411.0,01-05-2011,150,69.059548,68,NaN,NaN,...,18-03-2015,No,NaN,Broker,Never Enrolled,NaN,Non-MGA,No,182702,0
182703,9978,2017-02-28,ACTIVE,5411.0,01-05-2011,150,69.979466,69,NaN,NaN,...,18-03-2015,No,NaN,Broker,Never Enrolled,NaN,Non-MGA,No,182703,0
182739,9981,2017-01-31,ACTIVE,3999.0,01-05-2011,230,69.059548,68,60.0,18.0,...,19-12-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,182739,0
182740,9981,2017-02-28,ACTIVE,3999.0,01-05-2011,230,69.979466,69,60.0,18.0,...,19-12-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,182740,0
182765,9984,2017-01-31,ACTIVE,2066.0,01-05-2011,100,69.059548,68,NaN,NaN,...,12-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,No,182765,0
182766,9984,2017-02-28,ACTIVE,2066.0,01-05-2011,100,69.979466,69,NaN,NaN,...,12-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,No,182766,0
182791,9985,2017-01-31,ACTIVE,7382.0,01-04-2011,4500,70.045175,69,2.0,1.0,...,15-01-2012,No,In Force,Broker,In Force,NaN,Non-MGA,Yes,182791,0
182792,9985,2017-02-28,ACTIVE,7382.0,01-04-2011,4500,70.965092,70,2.0,1.0,...,15-01-2012,No,In Force,Broker,In Force,NaN,Non-MGA,Yes,182792,0
182817,9986,2017-01-31,ACTIVE,6029.0,01-05-2011,120,69.059548,68,NaN,NaN,...,30-11-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182817,0
182818,9986,2017-02-28,ACTIVE,6029.0,01-05-2011,120,69.979466,69,NaN,NaN,...,30-11-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182818,0
182843,9988,2017-01-31,ACTIVE,8099.0,01-05-2011,240,69.059548,68,NaN,NaN,...,29-03-2013,No,NaN,NaN,Duplicate,NaN,Non-MGA,No,182843,0
182844,9988,2017-02-28,ACTIVE,8099.0,01-05-2011,240,69.979466,69,NaN,NaN,...,29-03-2013,No,NaN,NaN,Duplicate,NaN,Non-MGA,No,182844,0
182869,9989,2017-01-31,ACTIVE,9191.0,01-05-2011,190,69.059548,68,NaN,NaN,...,31-03-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182869,0
182870,9989,2017-02-28,ACTIVE,9191.0,01-05-2011,190,69.979466,69,NaN,NaN,...,31-03-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182870,0
182918,9993,2017-01-31,ACTIVE,8059.0,01-06-2011,130,68.041068,67,NaN,NaN,...,15-05-2011,No,In Force,Field Force,In Force,NaN,Non-MGA,No,182918,0
182919,9993,2017-02-28,ACTIVE,8059.0,01-06-2011,130,68.960986,68,NaN,NaN,...,15-05-2011,No,In Force,Field Force,In Force,NaN,Non-MGA,No,182919,0
182944,9997,2017-01-31,ACTIVE,8299.0,01-05-2011,100,69.059548,68,NaN,NaN,...,14-03-2014,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182944,0
182945,9997,2017-02-28,ACTIVE,8299.0,01-05-2011,100,69.979466,69,NaN,NaN,...,14-03-2014,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182945,0
182970,9998,2017-01-31,ACTIVE,1711.0,01-05-2011,160,69.059548,68,29.0,5.0,...,15-03-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,182970,0
182971,9998,2017-02-28,ACTIVE,1711.0,01-05-2011,160,69.979466,69,29.0,5.0,...,15-03-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,182971,0
182996,A1,2017-01-31,ACTIVE,NaN,01-01-2010,3800,84.993840,84,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182996,0
182997,A1,2017-02-28,ACTIVE,NaN,01-01-2010,3800,85.913758,85,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182997,0

In [254]:
date

datetime.date(2017, 1, 30)

In [192]:
lapsed = data[data.STATUS == 'LAPSED' ].copy()
lapsed['freq'] = lapsed.groupby('GRPNUM')['GRPNUM'].transform('count')
lapsed = lapsed.drop_duplicates(subset = 'GRPNUM')
lapsed[lapsed.freq>1]

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y,freq
981,10053,2016-04-30,LAPSED,3089.0,01-10-2011,400,54.965092,54,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,981,0,2
9717,10599,2015-06-30,LAPSED,4214.0,01-01-2012,225,41.921971,41,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,9717,0,4
10065,10619,2016-07-31,LAPSED,4213.0,01-01-2012,110,54.965092,54,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,10065,0,2
11022,10679,2015-03-31,LAPSED,1521.0,01-01-2012,1500,38.932238,38,238.0,235.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,11022,0,2
15031,10931,2015-02-28,LAPSED,3999.0,01-01-2012,192,37.913758,37,2.0,0.0,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,15031,0,2
16717,11050,2016-02-29,LAPSED,2499.0,01-01-2012,115,49.938398,49,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,16717,0,2
22489,11406,2015-11-30,LAPSED,8011.0,01-01-2012,110,46.948665,46,10.0,9.0,...,No,Lapse-Pending,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,22489,0,2
24220,11517,2016-05-31,LAPSED,8221.0,01-02-2012,530,51.942505,51,251.0,240.0,...,No,NaN,Broker,Past Enrollment,N,Non-MGA,Yes,24220,0,2
25033,11563,2016-10-31,LAPSED,5812.0,01-01-2012,150,57.987680,57,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,25033,0,2
26552,11641,2016-05-31,LAPSED,8011.0,01-02-2012,400,51.942505,51,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,26552,0,2
27001,11663,2015-05-31,LAPSED,5082.0,01-02-2012,300,39.917864,39,10.0,10.0,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,Yes,27001,0,2
31191,11942,2015-03-31,LAPSED,5599.0,01-04-2012,110,35.942505,35,NaN,NaN,...,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,31191,0,2
32402,12030,2016-08-31,LAPSED,5599.0,01-04-2012,150,52.993840,52,NaN,NaN,...,No,NaN,Broker,Never Enrolled,NaN,Non-MGA,No,32402,0,2
34410,12169,2016-08-31,LAPSED,8741.0,01-06-2012,110,50.989733,50,NaN,NaN,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,No,34410,0,2
37107,12322,2016-10-31,LAPSED,4111.0,01-06-2012,150,52.993840,52,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,37107,0,2
39590,12470,2016-02-29,LAPSED,8082.0,01-08-2012,160,42.940452,42,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,39590,0,2
41432,12578,2016-09-30,LAPSED,9221.0,01-07-2012,560,50.989733,50,7.0,7.0,...,No,Cancelled,Field Force,Cancelled by Group,Y,Non-MGA,Yes,41432,0,2
41503,12581,2016-07-31,LAPSED,4952.0,01-07-2012,600,48.985626,48,3.0,2.0,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,Yes,41503,0,2
44563,12771,2015-07-31,LAPSED,9199.0,01-08-2012,120,36.041181,35,NaN,NaN,...,No,Lapse-Pending,Field Force,In Force,NaN,Non-MGA,Yes,44563,0,2
45546,12828,2015-06-30,LAPSED,5399.0,01-10-2012,6500,32.919918,32,764.0,760.0,...,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,45546,0,2
45602,12834,2015-01-31,LAPSED,4213.0,01-09-2012,300,28.977413,28,9.0,6.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,45602,0,2
45771,12847,2015-02-28,LAPSED,9199.0,01-09-2012,220,29.897331,29,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,45771,0,2
49396,13048,2015-09-30,LAPSED,8611.0,01-10-2012,2000,35.942505,35,2.0,2.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,49396,0,2
50183,13092,2015-01-31,LAPSED,3949.0,01-10-2012,13092,27.991786,27,27.0,22.0,...,No,NaN,Broker,In Force,NaN,Non-MGA,No,50183,0,2
50248,13098,2015-01-31,LAPSED,6411.0,01-11-2012,165,26.973306,26,6.0,6.0,...,Yes,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,50248,0,2
51145,13151,2015-03-31,LAPSED,1522.0,01-11-2012,120,28.911704,28,NaN,NaN,...,No,NaN,Broker,In Force,NaN,Non-MGA,No,51145,0,3
51690,13179,2015-11-30,LAPSED,9999.0,01-11-2012,130,36.928131,36,NaN,NaN,...,No,In Force,Field Force,In Force,NaN,Non-MGA,No,51690,0,2
56993,17073,2015-02-28,LAPSED,8299.0,01-12-2012,125,26.907598,26,NaN,NaN,...,Yes,NaN,Field Force,In Force,NaN,Non-MGA,No,56993,0,2
57347,17108,2016-02-29,LAPSED,6324.0,01-01-2013,4000,37.913758,37,792.0,746.0,...,No,NaN,Broker,Cancelled by Group,Y,Non-MGA,Yes,57347,0,2
66331,17806,2015-03-31,LAPSED,9999.0,01-03-2013,130,24.969199,24,NaN,NaN,...,No,In Force,Field Force,Cancelled by Group,NaN,Non-MGA,No,66331,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137570,3948,2015-03-31,LAPSED,3316.0,01-01-2011,538,50.924025,50,2.0,0.0,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,137570,0,2
137669,3956,2015-05-31,LAPSED,9191.0,01-02-2011,1500,51.909651,51,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,137669,0,2
138037,3979,2016-12-31,LAPSED,8221.0,01-01-2011,125,71.983573,71,NaN,NaN,...,No,NaN,NaN,In Force,NaN,Non-MGA,No,138037,0,2
138218,3994,2015-09-30,LAPSED,3999.0,01-01-2011,300,56.936345,56,NaN,NaN,...,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,138218,0,2
141957,5703,2016-04-30,LAPSED,7349.0,01-09-2011,189,55.950719,55,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,141957,0,2
145969,5979,2015-08-31,LAPSED,8299.0,01-10-2011,450,46.981520,46,19.0,19.0,...,No,Lapse-Pending,Broker,Cancelled by Group,NaN,Non-MGA,Yes,145969,0,2
150055,6613,2016-01-31,LAPSED,5699.0,01-01-2004,11000,508.977413,144,3149.0,3129.0,...,Yes,Cancelled,Broker,Cancelled by Group,Y,Non-MGA,Yes,150055,0,2
150837,6691,2015-01-31,LAPSED,8062.0,01-02-2007,2500,95.967146,95,96.0,0.0,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,150837,0,2
151037,6703,2016-04-30,LAPSED,3496.0,01-01-2010,200,75.926078,75,0.0,0.0,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,Yes,151037,0,2
152034,6792,2015-08-31,LAPSED,7011.0,01-07-2010,1100,61.995893,61,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,152034,0,2
152916,7087,2015-11-30,LAPSED,7011.0,01-07-2011,8000,52.993840,52,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,152916,0,2
153229,7108,2016-07-31,LAPSED,8611.0,01-05-2011,103,63.014374,62,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,153229,0,2
157114,7373,2015-09-30,LAPSED,3999.0,01-05-2011,230,52.993840,52,NaN,NaN,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,No,157114,0,2
157661,7405,2016-05-31,LAPSED,8082.0,01-06-2011,125,59.991786,59,12.0,12.0,...,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,157661,0,2
159325,7513,2015-10-31,LAPSED,179.0,01-07-2011,240,52.008214,51,NaN,NaN,...,No,Lapse-Pending,Field Force,In Force,NaN,Non-MGA,No,159325,0,2
160043,7553,2016-08-31,LAPSED,1541.0,01-08-2011,1300,61.010267,60,NaN,NaN,...,No,NaN,Broker,Cancelled by Group,N,Non-MGA,Yes,160043,0,2
160072,7560,2015-06-30,LAPSED,8082.0,01-08-2011,102,46.948665,46,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,160072,0,2
160460,7586,2015-05-31,LAPSED,8299.0,01-07-2011,127,46.981520,46,3.0,3.0,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,160460,0,2
163275,7751,2015-03-31,LAPSED,8211.0,01-09-2011,215,42.940452,42,NaN,NaN,...,No,Lapse-Pending,Field Force,In Force,NaN,Non-MGA,No,163275,0,2
163440,7765,2015-07-31,LAPSED,6029.0,01-08-2011,4800,48.098833,47,14.0,14.0,...,Yes,In Force,Broker,Cancelled by Group,Y,Non-MGA,Yes,163440,0,2
164617,7834,2015-05-31,LAPSED,1542.0,01-09-2011,140,44.944559,44,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,164617,0,2
168375,9075,2015-05-31,LAPSED,8059.0,01-02-2011,200,51.909651,51,17.0,17.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,168375,0,2
169060,9116,2015-05-31,LAPSED,2711.0,01-01-2011,160,52.928131,52,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,169060,0,2
173096,9362,2015-07-31,LAPSED,7373.0,01-02-2011,103,54.061771,53,2.0,2.0,...,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,No,173096,0,2
173639,9395,2016-05-31,LAPSED,9191.0,01-01-2011,425,64.952772,64,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,173639,0,2
174973,9486,2015-09-30,LAPSED,9191.0,01-01-2011,100,56.936345,56,NaN,NaN,...,No,In Force,Field Force,In Force,NaN,Non-MGA,No,174973,0,2
175642,9527,2016-04-30,LAPSED,8711.0,01-06-2011,34000,58.973306,58,2.0,2.0,...,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,175642,0,2
176425,9583,2015-10-31,LAPSED,8399.0,01-01-2011,250,57.954825,57,NaN,NaN,...,No,Lapse-Pending,Field Force,In Force,N,Non-MGA,No,176425,0,2
179502,9777,2016-01-31,LAPSED,7361.0,01-01-2011,115,60.977413,60,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,179502,0,2
181527,9900,2016-04-30,LAPSED,5014.0,01-06-2011,101,58.973306,58,NaN,NaN,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,181527,0,2

In [193]:
count = 0 ;
one_time_lapsed_grps = []
for i in lapsed.GRPNUM:
    if lapsed[lapsed.GRPNUM == i].freq.any() == 1:
        scan = len(data[data.GRPNUM == i])
        a = data[data.GRPNUM == i].STATUS
        if a.iloc[scan-1] != 'LAPSED':
            count = count + 1
            one_time_lapsed_grps.append(i)
print count

134

In [195]:
one_time_lapsed_grps

[10006,
 10053,
 10119,
 10560,
 10593,
 11050,
 11138,
 11177,
 11288,
 11289,
 11346,
 11710,
 11744,
 11800,
 11915,
 11942,
 11965,
 12117,
 12166,
 12193,
 12304,
 12494,
 12549,
 12583,
 12645,
 12679,
 12688,
 12771,
 12833,
 12877,
 12949,
 12966,
 13034,
 13046,
 13049,
 13137,
 13151,
 13179,
 16887,
 17042,
 17073,
 17374,
 17676,
 17721,
 18181,
 18207,
 18237,
 18300,
 18330,
 18356,
 18430,
 18518,
 19276,
 19290,
 19434,
 19634,
 19923,
 20023,
 20607,
 20771,
 20775,
 20886,
 21045,
 21266,
 21289,
 21292,
 21333,
 21345,
 21388,
 21416,
 21418,
 21424,
 21459,
 21551,
 21604,
 21693,
 21748,
 21834,
 21856,
 21918,
 22042,
 22161,
 22169,
 22296,
 22337,
 22490,
 22527,
 22582,
 22602,
 22755,
 22783,
 22784,
 22799,
 22847,
 22951,
 3047,
 3189,
 3256,
 3563,
 3608,
 3698,
 3730,
 3810,
 3956,
 4015,
 5567,
 5694,
 5714,
 5811,
 5960,
 6227,
 6449,
 7057,
 7063,
 7196,
 7231,
 7340,
 7405,
 7549,
 7571,
 7586,
 7662,
 7685,
 7740,
 7751,
 7834,
 9248,
 9395,
 9486,
 9527,
 9630,
 9669,
 9802,
 '9820']

In [196]:
multi_lapsed = lapsed[lapsed.freq > 1]
multi_lapsed

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y,freq
981,10053,2016-04-30,LAPSED,3089.0,01-10-2011,400,54.965092,54,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,981,0,2
9717,10599,2015-06-30,LAPSED,4214.0,01-01-2012,225,41.921971,41,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,9717,0,4
10065,10619,2016-07-31,LAPSED,4213.0,01-01-2012,110,54.965092,54,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,10065,0,2
11022,10679,2015-03-31,LAPSED,1521.0,01-01-2012,1500,38.932238,38,238.0,235.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,11022,0,2
15031,10931,2015-02-28,LAPSED,3999.0,01-01-2012,192,37.913758,37,2.0,0.0,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,15031,0,2
16717,11050,2016-02-29,LAPSED,2499.0,01-01-2012,115,49.938398,49,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,16717,0,2
22489,11406,2015-11-30,LAPSED,8011.0,01-01-2012,110,46.948665,46,10.0,9.0,...,No,Lapse-Pending,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,22489,0,2
24220,11517,2016-05-31,LAPSED,8221.0,01-02-2012,530,51.942505,51,251.0,240.0,...,No,NaN,Broker,Past Enrollment,N,Non-MGA,Yes,24220,0,2
25033,11563,2016-10-31,LAPSED,5812.0,01-01-2012,150,57.987680,57,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,25033,0,2
26552,11641,2016-05-31,LAPSED,8011.0,01-02-2012,400,51.942505,51,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,26552,0,2
27001,11663,2015-05-31,LAPSED,5082.0,01-02-2012,300,39.917864,39,10.0,10.0,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,Yes,27001,0,2
31191,11942,2015-03-31,LAPSED,5599.0,01-04-2012,110,35.942505,35,NaN,NaN,...,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,31191,0,2
32402,12030,2016-08-31,LAPSED,5599.0,01-04-2012,150,52.993840,52,NaN,NaN,...,No,NaN,Broker,Never Enrolled,NaN,Non-MGA,No,32402,0,2
34410,12169,2016-08-31,LAPSED,8741.0,01-06-2012,110,50.989733,50,NaN,NaN,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,No,34410,0,2
37107,12322,2016-10-31,LAPSED,4111.0,01-06-2012,150,52.993840,52,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,37107,0,2
39590,12470,2016-02-29,LAPSED,8082.0,01-08-2012,160,42.940452,42,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,39590,0,2
41432,12578,2016-09-30,LAPSED,9221.0,01-07-2012,560,50.989733,50,7.0,7.0,...,No,Cancelled,Field Force,Cancelled by Group,Y,Non-MGA,Yes,41432,0,2
41503,12581,2016-07-31,LAPSED,4952.0,01-07-2012,600,48.985626,48,3.0,2.0,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,Yes,41503,0,2
44563,12771,2015-07-31,LAPSED,9199.0,01-08-2012,120,36.041181,35,NaN,NaN,...,No,Lapse-Pending,Field Force,In Force,NaN,Non-MGA,Yes,44563,0,2
45546,12828,2015-06-30,LAPSED,5399.0,01-10-2012,6500,32.919918,32,764.0,760.0,...,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,45546,0,2
45602,12834,2015-01-31,LAPSED,4213.0,01-09-2012,300,28.977413,28,9.0,6.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,45602,0,2
45771,12847,2015-02-28,LAPSED,9199.0,01-09-2012,220,29.897331,29,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,45771,0,2
49396,13048,2015-09-30,LAPSED,8611.0,01-10-2012,2000,35.942505,35,2.0,2.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,49396,0,2
50183,13092,2015-01-31,LAPSED,3949.0,01-10-2012,13092,27.991786,27,27.0,22.0,...,No,NaN,Broker,In Force,NaN,Non-MGA,No,50183,0,2
50248,13098,2015-01-31,LAPSED,6411.0,01-11-2012,165,26.973306,26,6.0,6.0,...,Yes,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,50248,0,2
51145,13151,2015-03-31,LAPSED,1522.0,01-11-2012,120,28.911704,28,NaN,NaN,...,No,NaN,Broker,In Force,NaN,Non-MGA,No,51145,0,3
51690,13179,2015-11-30,LAPSED,9999.0,01-11-2012,130,36.928131,36,NaN,NaN,...,No,In Force,Field Force,In Force,NaN,Non-MGA,No,51690,0,2
56993,17073,2015-02-28,LAPSED,8299.0,01-12-2012,125,26.907598,26,NaN,NaN,...,Yes,NaN,Field Force,In Force,NaN,Non-MGA,No,56993,0,2
57347,17108,2016-02-29,LAPSED,6324.0,01-01-2013,4000,37.913758,37,792.0,746.0,...,No,NaN,Broker,Cancelled by Group,Y,Non-MGA,Yes,57347,0,2
66331,17806,2015-03-31,LAPSED,9999.0,01-03-2013,130,24.969199,24,NaN,NaN,...,No,In Force,Field Force,Cancelled by Group,NaN,Non-MGA,No,66331,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137570,3948,2015-03-31,LAPSED,3316.0,01-01-2011,538,50.924025,50,2.0,0.0,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,137570,0,2
137669,3956,2015-05-31,LAPSED,9191.0,01-02-2011,1500,51.909651,51,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,137669,0,2
138037,3979,2016-12-31,LAPSED,8221.0,01-01-2011,125,71.983573,71,NaN,NaN,...,No,NaN,NaN,In Force,NaN,Non-MGA,No,138037,0,2
138218,3994,2015-09-30,LAPSED,3999.0,01-01-2011,300,56.936345,56,NaN,NaN,...,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,138218,0,2
141957,5703,2016-04-30,LAPSED,7349.0,01-09-2011,189,55.950719,55,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,141957,0,2
145969,5979,2015-08-31,LAPSED,8299.0,01-10-2011,450,46.981520,46,19.0,19.0,...,No,Lapse-Pending,Broker,Cancelled by Group,NaN,Non-MGA,Yes,145969,0,2
150055,6613,2016-01-31,LAPSED,5699.0,01-01-2004,11000,508.977413,144,3149.0,3129.0,...,Yes,Cancelled,Broker,Cancelled by Group,Y,Non-MGA,Yes,150055,0,2
150837,6691,2015-01-31,LAPSED,8062.0,01-02-2007,2500,95.967146,95,96.0,0.0,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,150837,0,2
151037,6703,2016-04-30,LAPSED,3496.0,01-01-2010,200,75.926078,75,0.0,0.0,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,Yes,151037,0,2
152034,6792,2015-08-31,LAPSED,7011.0,01-07-2010,1100,61.995893,61,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,152034,0,2
152916,7087,2015-11-30,LAPSED,7011.0,01-07-2011,8000,52.993840,52,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,152916,0,2
153229,7108,2016-07-31,LAPSED,8611.0,01-05-2011,103,63.014374,62,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,153229,0,2
157114,7373,2015-09-30,LAPSED,3999.0,01-05-2011,230,52.993840,52,NaN,NaN,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,No,157114,0,2
157661,7405,2016-05-31,LAPSED,8082.0,01-06-2011,125,59.991786,59,12.0,12.0,...,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,157661,0,2
159325,7513,2015-10-31,LAPSED,179.0,01-07-2011,240,52.008214,51,NaN,NaN,...,No,Lapse-Pending,Field Force,In Force,NaN,Non-MGA,No,159325,0,2
160043,7553,2016-08-31,LAPSED,1541.0,01-08-2011,1300,61.010267,60,NaN,NaN,...,No,NaN,Broker,Cancelled by Group,N,Non-MGA,Yes,160043,0,2
160072,7560,2015-06-30,LAPSED,8082.0,01-08-2011,102,46.948665,46,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,160072,0,2
160460,7586,2015-05-31,LAPSED,8299.0,01-07-2011,127,46.981520,46,3.0,3.0,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,160460,0,2
163275,7751,2015-03-31,LAPSED,8211.0,01-09-2011,215,42.940452,42,NaN,NaN,...,No,Lapse-Pending,Field Force,In Force,NaN,Non-MGA,No,163275,0,2
163440,7765,2015-07-31,LAPSED,6029.0,01-08-2011,4800,48.098833,47,14.0,14.0,...,Yes,In Force,Broker,Cancelled by Group,Y,Non-MGA,Yes,163440,0,2
164617,7834,2015-05-31,LAPSED,1542.0,01-09-2011,140,44.944559,44,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,164617,0,2
168375,9075,2015-05-31,LAPSED,8059.0,01-02-2011,200,51.909651,51,17.0,17.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,168375,0,2
169060,9116,2015-05-31,LAPSED,2711.0,01-01-2011,160,52.928131,52,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,169060,0,2
173096,9362,2015-07-31,LAPSED,7373.0,01-02-2011,103,54.061771,53,2.0,2.0,...,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,No,173096,0,2
173639,9395,2016-05-31,LAPSED,9191.0,01-01-2011,425,64.952772,64,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,173639,0,2
174973,9486,2015-09-30,LAPSED,9191.0,01-01-2011,100,56.936345,56,NaN,NaN,...,No,In Force,Field Force,In Force,NaN,Non-MGA,No,174973,0,2
175642,9527,2016-04-30,LAPSED,8711.0,01-06-2011,34000,58.973306,58,2.0,2.0,...,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,175642,0,2
176425,9583,2015-10-31,LAPSED,8399.0,01-01-2011,250,57.954825,57,NaN,NaN,...,No,Lapse-Pending,Field Force,In Force,N,Non-MGA,No,176425,0,2
179502,9777,2016-01-31,LAPSED,7361.0,01-01-2011,115,60.977413,60,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,179502,0,2
181527,9900,2016-04-30,LAPSED,5014.0,01-06-2011,101,58.973306,58,NaN,NaN,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,181527,0,2

In [197]:
multiple_time_lapsed_grps = []
for i in multi_lapsed.GRPNUM:
    multiple_time_lapsed_grps.append(i)

In [198]:
multiple_time_lapsed_grps

[10053,
 10599,
 10619,
 10679,
 10931,
 11050,
 11406,
 11517,
 11563,
 11641,
 11663,
 11942,
 12030,
 12169,
 12322,
 12470,
 12578,
 12581,
 12771,
 12828,
 12834,
 12847,
 13048,
 13092,
 13098,
 13151,
 13179,
 17073,
 17108,
 17806,
 18037,
 18146,
 18272,
 18430,
 18444,
 18451,
 18758,
 18804,
 19300,
 19389,
 19585,
 19916,
 19948,
 19952,
 20059,
 20076,
 20078,
 20085,
 20151,
 20254,
 20256,
 20257,
 20269,
 20312,
 20554,
 20590,
 20633,
 20662,
 20973,
 21121,
 21155,
 21182,
 21187,
 21424,
 21563,
 21564,
 21604,
 21659,
 21681,
 21693,
 21872,
 22028,
 22098,
 22441,
 22504,
 22582,
 22646,
 22877,
 3374,
 3517,
 3703,
 3751,
 3862,
 3948,
 3956,
 3979,
 3994,
 5703,
 5979,
 6613,
 6691,
 6703,
 6792,
 7087,
 7108,
 7373,
 7405,
 7513,
 7553,
 7560,
 7586,
 7751,
 7765,
 7834,
 9075,
 9116,
 9362,
 9395,
 9486,
 9527,
 9583,
 9777,
 '9900']

In [243]:
def lapsed_group_treatment(data , GRPNUM , frequency):
    instances = len(data[data.GRPNUM == GRPNUM])
    for i in range(0,instances):
        if frequency.any() == 0:
            break
        else:
            if data[data.GRPNUM == GRPNUM].iloc[i].STATUS == 'LAPSED':
                key = data[data.GRPNUM == GRPNUM].iloc[i].sno
                #print key
                data.iloc[key,2] = 'ACTIVE'
                frequency = frequency - 1
                #print 'success'

In [244]:
for GRPNUM in multiple_time_lapsed_grps:
    frequency = lapsed[lapsed.GRPNUM == GRPNUM].freq
    lapsed_group_treatment(data , GRPNUM , frequency)

In [245]:
for GRPNUM in one_time_lapsed_grps:
    frequency = lapsed[lapsed.GRPNUM == GRPNUM].freq
    lapsed_group_treatment(data , GRPNUM , frequency)

In [149]:
data.loc[981].STATUS = 'ACTIVE'

In [150]:
data.loc[981].STATUS

'LAPSED'

In [201]:
data[data.GRPNUM == 10053]

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
966,10053,2015-01-31,ACTIVE,3089.0,01-10-2011,400,40.016427,39,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,966,0
967,10053,2015-02-28,ACTIVE,3089.0,01-10-2011,400,40.936345,40,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,967,0
968,10053,2015-03-31,ACTIVE,3089.0,01-10-2011,400,41.954825,41,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,968,0
969,10053,2015-04-30,ACTIVE,3089.0,01-10-2011,400,42.940452,42,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,969,0
970,10053,2015-05-31,ACTIVE,3089.0,01-10-2011,400,43.958932,43,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,970,0
971,10053,2015-06-30,ACTIVE,3089.0,01-10-2011,400,44.944559,44,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,971,0
972,10053,2015-07-31,ACTIVE,3089.0,01-10-2011,400,46.089224,45,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,972,0
973,10053,2015-08-31,ACTIVE,3089.0,01-10-2011,400,46.981520,46,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,973,0
974,10053,2015-09-30,ACTIVE,3089.0,01-10-2011,400,47.967146,47,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,974,0
975,10053,2015-10-31,ACTIVE,3089.0,01-10-2011,400,48.985626,48,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,975,0
976,10053,2015-11-30,ACTIVE,3089.0,01-10-2011,400,49.971253,49,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,976,0
977,10053,2015-12-31,ACTIVE,3089.0,01-10-2011,400,50.989733,50,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,977,0
978,10053,2016-01-31,ACTIVE,3089.0,01-10-2011,400,52.008214,51,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,978,0
979,10053,2016-02-29,ACTIVE,3089.0,01-10-2011,400,52.960986,52,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,979,0
980,10053,2016-03-31,ACTIVE,3089.0,01-10-2011,400,53.979466,53,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,980,0
981,10053,2016-04-30,ACTIVE,3089.0,01-10-2011,400,54.965092,54,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,981,0
982,10053,2016-06-30,Active,3089.0,01-10-2011,400,56.987700,56,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,982,0
983,10053,2016-07-31,ACTIVE,3089.0,01-10-2011,400,57.987680,57,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,983,0
984,10053,2016-08-31,ACTIVE,3089.0,01-10-2011,400,59.006160,58,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,984,0
985,10053,2016-09-30,ACTIVE,3089.0,01-10-2011,400,59.991786,59,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,985,0
986,10053,2016-10-31,ACTIVE,3089.0,01-10-2011,400,61.010267,60,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,986,0
987,10053,2016-11-30,ACTIVE,3089.0,01-10-2011,400,61.995893,61,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,987,0
988,10053,2016-12-31,ACTIVE,3089.0,01-10-2011,400,63.014374,62,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,988,0
989,10053,2017-01-31,ACTIVE,3089.0,01-10-2011,400,64.032854,63,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,989,0
990,10053,2017-02-28,ACTIVE,3089.0,01-10-2011,400,64.952772,64,NaN,NaN,...,01-09-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,990,0

In [246]:
data[data.GRPNUM == 10006]

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
52,10006,2015-01-31,ACTIVE,8211.0,01-11-2011,3500,38.997947,38,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,52,7
53,10006,2015-02-28,ACTIVE,8211.0,01-11-2011,3500,39.917864,39,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,53,7
54,10006,2015-03-31,ACTIVE,8211.0,01-11-2011,3500,40.936345,40,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,54,7
55,10006,2015-04-30,ACTIVE,8211.0,01-11-2011,3500,41.921971,41,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,55,7
56,10006,2015-05-31,ACTIVE,8211.0,01-11-2011,3500,42.940452,42,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,56,7
57,10006,2015-06-30,ACTIVE,8211.0,01-11-2011,3500,43.926078,43,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,57,7
58,10006,2015-07-31,ACTIVE,8211.0,01-11-2011,3500,45.067948,44,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,58,7
59,10006,2015-08-31,ACTIVE,8211.0,01-11-2011,3500,45.963039,45,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,59,7
60,10006,2015-09-30,ACTIVE,8211.0,01-11-2011,3500,46.948665,46,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,60,7
61,10006,2015-10-31,ACTIVE,8211.0,01-11-2011,3500,47.967146,47,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,61,7
62,10006,2015-11-30,ACTIVE,8211.0,01-11-2011,3500,48.952772,48,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,62,7
63,10006,2015-12-31,ACTIVE,8211.0,01-11-2011,3500,49.971253,49,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,63,7
64,10006,2016-01-31,ACTIVE,8211.0,01-11-2011,3500,50.989733,50,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,64,7
65,10006,2016-02-29,ACTIVE,8211.0,01-11-2011,3500,51.942505,51,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,65,7
66,10006,2016-03-31,ACTIVE,8211.0,01-11-2011,3500,52.960986,52,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,66,7
67,10006,2016-04-30,ACTIVE,8211.0,01-11-2011,3500,53.946612,53,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,67,7
68,10006,2016-05-31,ACTIVE,8211.0,01-11-2011,3500,54.965092,54,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,68,7
69,10006,2016-06-30,Active,8211.0,01-11-2011,3500,54.965100,55,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,69,7
70,10006,2016-07-31,ACTIVE,8211.0,01-11-2011,3500,56.969199,56,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,70,7
71,10006,2016-08-31,ACTIVE,8211.0,01-11-2011,3500,57.987680,57,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,71,3
72,10006,2016-09-30,ACTIVE,8211.0,01-11-2011,3500,58.973306,58,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,72,2
73,10006,2016-10-31,ACTIVE,8211.0,01-11-2011,3500,59.991786,59,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,73,1
74,10006,2016-11-30,ACTIVE,8211.0,01-11-2011,3500,60.977413,60,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,74,0
75,10006,2016-12-31,ACTIVE,8211.0,01-11-2011,3500,61.995893,61,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,75,7
76,10006,2017-01-31,ACTIVE,8211.0,01-11-2011,3500,63.014374,62,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,76,7
77,10006,2017-02-28,ACTIVE,8211.0,01-11-2011,3500,63.934292,63,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,77,7

In [75]:
lapsed[lapsed.GRPNUM == 10053].freq

981    2
Name: freq, dtype: int64

In [165]:
data

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,index,y
0,10001,2015-01-31,ACTIVE,8299.0,01-01-2012,1900,36.993840,36,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,0,0
1,10001,2015-02-28,ACTIVE,8299.0,01-01-2012,1900,37.913758,37,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,1,0
2,10001,2015-03-31,ACTIVE,8299.0,01-01-2012,1900,38.932238,38,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,2,0
3,10001,2015-04-30,ACTIVE,8299.0,01-01-2012,1900,39.917864,39,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,3,0
4,10001,2015-05-31,ACTIVE,8299.0,01-01-2012,1900,40.936345,40,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,4,0
5,10001,2015-06-30,ACTIVE,8299.0,01-01-2012,1900,41.921971,41,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,5,0
6,10001,2015-07-31,ACTIVE,8299.0,01-01-2012,1900,43.058339,42,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,6,0
7,10001,2015-08-31,ACTIVE,8299.0,01-01-2012,1900,43.958932,43,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,7,0
8,10001,2015-09-30,ACTIVE,8299.0,01-01-2012,1900,44.944559,44,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,8,0
9,10001,2015-10-31,ACTIVE,8299.0,01-01-2012,1900,45.963039,45,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,9,0
10,10001,2015-11-30,ACTIVE,8299.0,01-01-2012,1900,46.948665,46,16.0,16.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,10,0
11,10001,2015-12-31,ACTIVE,8299.0,01-01-2012,1900,47.967146,47,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,11,0
12,10001,2016-01-31,ACTIVE,8299.0,01-01-2012,1900,48.985626,48,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,12,0
13,10001,2016-02-29,ACTIVE,8299.0,01-01-2012,1900,49.938398,49,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,13,0
14,10001,2016-03-31,ACTIVE,8299.0,01-01-2012,1900,50.956879,50,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,14,0
15,10001,2016-04-30,ACTIVE,8299.0,01-01-2012,1900,51.942505,51,NaN,NaN,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,15,0
16,10001,2016-05-31,ACTIVE,8299.0,01-01-2012,1900,52.960986,52,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,16,0
17,10001,2016-06-30,Active,8299.0,01-01-2012,1900,52.961000,53,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,17,0
18,10001,2016-07-31,ACTIVE,8299.0,01-01-2012,1900,54.965092,54,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,18,0
19,10001,2016-08-31,ACTIVE,8299.0,01-01-2012,1900,55.983573,55,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,19,0
20,10001,2016-09-30,ACTIVE,8299.0,01-01-2012,1900,56.969199,56,1.0,1.0,...,01-12-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,20,0
21,10001,2016-10-31,ACTIVE,8299.0,01-01-2012,1900,57.987680,57,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,21,0
22,10001,2016-11-30,ACTIVE,8299.0,01-01-2012,1900,58.973306,58,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,22,0
23,10001,2016-12-31,ACTIVE,8299.0,01-01-2012,1900,59.991786,59,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,23,0
24,10001,2017-01-31,ACTIVE,8299.0,01-01-2012,1900,61.010267,60,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,24,0
25,10001,2017-02-28,ACTIVE,8299.0,01-01-2012,1900,61.930185,61,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,25,0
26,10003,2015-01-31,ACTIVE,5211.0,01-01-2012,200,36.993840,36,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,26,0
27,10003,2015-02-28,ACTIVE,5211.0,01-01-2012,200,37.913758,37,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,27,0
28,10003,2015-03-31,ACTIVE,5211.0,01-01-2012,200,38.932238,38,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,28,0
29,10003,2015-04-30,ACTIVE,5211.0,01-01-2012,200,39.917864,39,NaN,NaN,...,15-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182989,A1,2016-06-30,Active,NaN,01-01-2010,3800,76.944600,77,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182989,0
182990,A1,2016-07-31,ACTIVE,NaN,01-01-2010,3800,78.948665,78,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182990,0
182991,A1,2016-08-31,ACTIVE,NaN,01-01-2010,3800,79.967146,79,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182991,0
182992,A1,2016-09-30,ACTIVE,NaN,01-01-2010,3800,80.952772,80,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182992,0
182993,A1,2016-10-31,ACTIVE,NaN,01-01-2010,3800,81.971253,81,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182993,0
182994,A1,2016-11-30,ACTIVE,NaN,01-01-2010,3800,82.956879,82,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182994,0
182995,A1,2016-12-31,ACTIVE,NaN,01-01-2010,3800,83.975359,83,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182995,0
182996,A1,2017-01-31,ACTIVE,NaN,01-01-2010,3800,84.993840,84,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182996,0
182997,A1,2017-02-28,ACTIVE,NaN,01-01-2010,3800,85.913758,85,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182997,0
182998,A2,2015-01-31,ACTIVE,NaN,01-03-2010,200,59.039014,58,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182998,0
182999,A2,2015-02-28,ACTIVE,NaN,01-03-2010,200,59.958932,59,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182999,0
183000,A2,2015-03-31,ACTIVE,NaN,01-03-2010,200,60.977413,60,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183000,0
183001,A2,2015-04-30,ACTIVE,NaN,01-03-2010,200,61.963039,61,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183001,0
183002,A2,2015-05-31,ACTIVE,NaN,01-03-2010,200,62.981520,62,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183002,0
183003,A2,2015-06-30,ACTIVE,NaN,01-03-2010,200,63.967146,63,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183003,0
183004,A2,2015-07-31,ACTIVE,NaN,01-03-2010,200,65.164036,64,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183004,0
183005,A2,2015-08-31,ACTIVE,NaN,01-03-2010,200,66.004107,65,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183005,0
183006,A2,2015-09-30,ACTIVE,NaN,01-03-2010,200,66.989733,66,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183006,0
183007,A2,2015-10-31,ACTIVE,NaN,01-03-2010,200,68.008214,67,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183007,0
183008,A2,2015-11-30,ACTIVE,NaN,01-03-2010,200,68.993840,68,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183008,0
183009,A2,2015-12-31,ACTIVE,NaN,01-03-2010,200,70.012320,69,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183009,0
183010,A2,2016-01-31,ACTIVE,NaN,01-03-2010,200,71.030801,70,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183010,0
183011,A2,2016-02-29,ACTIVE,NaN,01-03-2010,200,71.983573,71,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183011,0
183012,A2,2016-03-31,ACTIVE,NaN,01-03-2010,200,73.002053,72,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183012,0
183013,A2,2016-04-30,ACTIVE,NaN,01-03-2010,200,73.987680,73,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183013,0
183014,A2,2016-05-31,ACTIVE,NaN,01-03-2010,200,75.006160,74,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183014,0
183015,A2,2016-06-30,Active,NaN,01-03-2010,200,75.006200,75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183015,0
183016,A2,2016-07-31,ACTIVE,NaN,01-03-2010,200,77.010267,76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183016,0
183017,A2,2016-08-31,ACTIVE,NaN,01-03-2010,200,78.028747,77,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183017,0
183018,A2,2016-09-30,LAPSED,NaN,01-03-2010,200,79.014374,78,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183018,0

In [237]:
start_date = datetime.datetime.strptime('17-01-31', '%y-%m-%d').date()
end_date = datetime.datetime.strptime('17-02-28', '%y-%m-%d').date()

In [231]:
start = time.time()
x = data[data.VALUATION == start_date]
end = time.time()
print end-start
x

0.00996112823486

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
24,10001,2017-01-31,ACTIVE,8299.0,01-01-2012,1900,61.010267,60,1.0,1.0,...,15-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,24,3
50,10003,2017-01-31,ACTIVE,5211.0,01-01-2012,200,61.010267,60,NaN,NaN,...,30-11-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,50,3
76,10006,2017-01-31,ACTIVE,8211.0,01-11-2011,3500,63.014374,62,NaN,NaN,...,30-09-2011,No,NaN,Broker,In Force,NaN,Non-MGA,No,76,3
102,10007,2017-01-31,ACTIVE,8051.0,01-11-2011,215,63.014374,62,NaN,NaN,...,01-12-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,102,0
128,10008,2017-01-31,ACTIVE,8099.0,01-10-2011,273,64.032854,63,NaN,NaN,...,30-09-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,No,128,0
154,10009,2017-01-31,ACTIVE,5511.0,01-10-2011,180,64.032854,63,NaN,NaN,...,25-03-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,154,0
180,10011,2017-01-31,ACTIVE,8299.0,01-11-2011,132,63.014374,62,NaN,NaN,...,10-10-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,180,0
206,10012,2017-01-31,ACTIVE,8399.0,01-10-2011,151,64.032854,63,1.0,0.0,...,15-08-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,206,0
236,10015,2017-01-31,ACTIVE,8062.0,01-10-2011,165,64.032854,63,12.0,4.0,...,10-12-2016,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,236,0
262,10016,2017-01-31,ACTIVE,8734.0,01-10-2011,360,64.032854,63,NaN,NaN,...,02-12-2016,Yes,NaN,Broker,Never Enrolled,NaN,Non-MGA,Yes,262,0
288,10017,2017-01-31,ACTIVE,8211.0,01-10-2011,625,64.032854,63,1.0,0.0,...,02-12-2016,No,NaN,Field Force,No Apps Taken,NaN,Non-MGA,Yes,288,0
324,10019,2017-01-31,ACTIVE,8299.0,01-10-2011,440,64.032854,63,NaN,NaN,...,22-12-2016,No,NaN,Field Force,No Apps Taken,NaN,Non-MGA,No,324,0
350,10020,2017-01-31,ACTIVE,7011.0,01-10-2011,200,64.032854,63,NaN,NaN,...,26-08-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,350,0
376,10021,2017-01-31,ACTIVE,9199.0,01-10-2011,100,64.032854,63,NaN,NaN,...,04-12-2015,No,NaN,Field Force,Never Enrolled,NaN,Non-MGA,No,376,0
402,10025,2017-01-31,ACTIVE,5812.0,01-11-2011,145,63.014374,62,NaN,NaN,...,30-09-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,402,0
428,10027,2017-01-31,ACTIVE,9199.0,01-02-2014,750,35.975359,35,28.0,5.0,...,11-11-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,428,0
454,10029,2017-01-31,ACTIVE,9311.0,01-10-2011,101,64.032854,63,7.0,7.0,...,30-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,454,0
480,1003,2017-01-31,ACTIVE,8211.0,01-11-1992,200,290.989733,290,NaN,NaN,...,20-11-2010,No,NaN,Field Force,In Force,NaN,Non-MGA,No,480,0
506,10030,2017-01-31,ACTIVE,8062.0,01-10-2011,1017,64.032854,63,16.0,12.0,...,15-09-2016,No,Lapse-Pending,Broker,In Force,NaN,Non-MGA,Yes,506,0
532,10031,2017-01-31,ACTIVE,8299.0,01-10-2011,150,64.032854,63,20.0,16.0,...,04-05-2016,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,532,0
558,10032,2017-01-31,ACTIVE,6732.0,01-10-2011,320,64.032854,63,NaN,NaN,...,02-12-2016,No,NaN,Field Force,No Apps Taken,NaN,Non-MGA,Yes,558,0
584,10033,2017-01-31,ACTIVE,8641.0,01-10-2011,450,64.032854,63,NaN,NaN,...,19-08-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,584,0
610,10035,2017-01-31,ACTIVE,8211.0,01-10-2011,115,64.032854,63,NaN,NaN,...,31-08-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,610,0
636,10037,2017-01-31,ACTIVE,6732.0,01-10-2011,100,64.032854,63,1.0,1.0,...,28-08-2015,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,636,0
662,10038,2017-01-31,ACTIVE,8211.0,01-10-2011,143,64.032854,63,5.0,2.0,...,15-12-2016,No,NaN,Broker,In Force,N,Non-MGA,Yes,662,0
688,10039,2017-01-31,ACTIVE,8211.0,01-10-2011,200,64.032854,63,NaN,NaN,...,20-08-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,688,0
714,10040,2017-01-31,ACTIVE,9199.0,01-10-2011,100,64.032854,63,NaN,NaN,...,25-09-2016,No,NaN,Broker,In Force,NaN,Non-MGA,No,714,0
740,10041,2017-01-31,ACTIVE,8221.0,01-10-2011,200,64.032854,63,NaN,NaN,...,30-08-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,740,0
805,10045,2017-01-31,ACTIVE,9199.0,01-10-2011,120,64.032854,63,NaN,NaN,...,27-08-2015,No,NaN,Field Force,In Force,NaN,Non-MGA,No,805,0
834,10047,2017-01-31,ACTIVE,8082.0,01-10-2011,160,64.032854,63,10.0,15.0,...,30-08-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,834,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182138,9941,2017-01-31,ACTIVE,5812.0,01-06-2011,175,68.041068,67,NaN,NaN,...,29-04-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182138,0
182164,9944,2017-01-31,ACTIVE,3731.0,01-05-2011,130,69.059548,68,1.0,0.0,...,08-04-2014,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,182164,0
182213,9946,2017-01-31,ACTIVE,3452.0,01-05-2011,116,69.059548,68,NaN,NaN,...,04-05-2016,No,In Force,Field Force,In Force,NaN,Non-MGA,Yes,182213,0
182239,9947,2017-01-31,ACTIVE,8211.0,01-06-2011,500,68.041068,67,NaN,NaN,...,29-04-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182239,0
182265,9948,2017-01-31,ACTIVE,8062.0,01-05-2011,115,69.059548,68,9.0,9.0,...,01-04-2016,No,In Force,Field Force,In Force,NaN,Non-MGA,Yes,182265,0
182291,9950,2017-01-31,ACTIVE,7381.0,01-05-2011,140,69.059548,68,NaN,NaN,...,31-03-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182291,0
182317,9951,2017-01-31,ACTIVE,8062.0,01-05-2011,385,69.059548,68,4.0,4.0,...,11-03-2016,No,NaN,Field Force,In Force,N,Non-MGA,Yes,182317,0
182343,9952,2017-01-31,ACTIVE,6029.0,01-05-2011,160,69.059548,68,29.0,29.0,...,20-04-2016,No,In Force,Broker,Past Enrollment,NaN,Non-MGA,Yes,182343,0
182369,9953,2017-01-31,ACTIVE,9199.0,01-06-2011,116,69.059548,67,1.0,1.0,...,15-05-2016,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,Yes,182369,0
182416,9959,2017-01-31,ACTIVE,1442.0,01-06-2011,320,68.041068,67,NaN,NaN,...,30-04-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182416,0
182457,9964,2017-01-31,ACTIVE,9199.0,01-05-2011,175,69.059548,68,9.0,0.0,...,20-11-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,182457,0
182483,9965,2017-01-31,ACTIVE,5813.0,01-06-2011,1300,68.041068,67,4.0,2.0,...,13-03-2016,No,NaN,Broker,In Force,NaN,Non-MGA,Yes,182483,0
182509,9966,2017-01-31,ACTIVE,8221.0,01-05-2011,305,69.059548,68,NaN,NaN,...,10-11-2015,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,182509,0
182535,9968,2017-01-31,ACTIVE,9191.0,01-05-2011,162,69.059548,68,NaN,NaN,...,31-12-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182535,0
182570,9970,2017-01-31,ACTIVE,5411.0,01-05-2011,525,69.059548,68,NaN,NaN,...,14-04-2015,No,NaN,Broker,In Force,NaN,Non-MGA,No,182570,0
182598,9973,2017-01-31,ACTIVE,9191.0,01-06-2011,100,68.041068,67,NaN,NaN,...,30-04-2011,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182598,0
182624,9974,2017-01-31,ACTIVE,5045.0,01-06-2011,13989,68.041068,67,57.0,51.0,...,28-11-2016,No,NaN,Broker,In Force,Y,Non-MGA,Yes,182624,0
182650,9975,2017-01-31,ACTIVE,8099.0,01-07-2011,10400,67.055441,66,192.0,192.0,...,20-05-2016,No,NaN,Broker,In Force,Y,Non-MGA,Yes,182650,0
182676,9977,2017-01-31,ACTIVE,3714.0,01-05-2011,119,69.059548,68,NaN,NaN,...,13-02-2016,No,NaN,Field Force,Never Enrolled,NaN,Non-MGA,Yes,182676,0
182702,9978,2017-01-31,ACTIVE,5411.0,01-05-2011,150,69.059548,68,NaN,NaN,...,18-03-2015,No,NaN,Broker,Never Enrolled,NaN,Non-MGA,No,182702,0
182739,9981,2017-01-31,ACTIVE,3999.0,01-05-2011,230,69.059548,68,60.0,18.0,...,19-12-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,182739,0
182765,9984,2017-01-31,ACTIVE,2066.0,01-05-2011,100,69.059548,68,NaN,NaN,...,12-12-2014,No,NaN,Broker,Past Enrollment,NaN,Non-MGA,No,182765,0
182791,9985,2017-01-31,ACTIVE,7382.0,01-04-2011,4500,70.045175,69,2.0,1.0,...,15-01-2012,No,In Force,Broker,In Force,NaN,Non-MGA,Yes,182791,0
182817,9986,2017-01-31,ACTIVE,6029.0,01-05-2011,120,69.059548,68,NaN,NaN,...,30-11-2013,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182817,0
182843,9988,2017-01-31,ACTIVE,8099.0,01-05-2011,240,69.059548,68,NaN,NaN,...,29-03-2013,No,NaN,NaN,Duplicate,NaN,Non-MGA,No,182843,0
182869,9989,2017-01-31,ACTIVE,9191.0,01-05-2011,190,69.059548,68,NaN,NaN,...,31-03-2012,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182869,0
182918,9993,2017-01-31,ACTIVE,8059.0,01-06-2011,130,68.041068,67,NaN,NaN,...,15-05-2011,No,In Force,Field Force,In Force,NaN,Non-MGA,No,182918,0
182944,9997,2017-01-31,ACTIVE,8299.0,01-05-2011,100,69.059548,68,NaN,NaN,...,14-03-2014,No,NaN,Field Force,In Force,NaN,Non-MGA,No,182944,0
182970,9998,2017-01-31,ACTIVE,1711.0,01-05-2011,160,69.059548,68,29.0,5.0,...,15-03-2016,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,182970,0
182996,A1,2017-01-31,ACTIVE,NaN,01-01-2010,3800,84.993840,84,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182996,0

In [287]:
start = time.time()
for i in range(140000,160000):
    j=0
    for j in range(1,4):
        if data.iloc[i,1].date() > start_date:
            break
        if data.iloc[i].STATUS == 'LAPSED':
            data['y'].iloc[i] = 0 
            break
        if data.iloc[i+j].STATUS == 'LAPSED':
            data['y'].iloc[i] = j
            break
        if data.iloc[i+3].STATUS != 'LAPSED':
            data['y'].iloc[i] = 12
end = time.time()
print end-start

1738.07521796

In [288]:
start = time.time()
for i in range(160000,183019):
    j=0
    for j in range(1,4):
        if data.iloc[i,1].date() > start_date:
            break
        if data.iloc[i].STATUS == 'LAPSED':
            data['y'].iloc[i] = 0 
            break
        if data.iloc[i+j].STATUS == 'LAPSED':
            data['y'].iloc[i] = j
            break
        if data.iloc[i+3].STATUS != 'LAPSED':
            data['y'].iloc[i] = 12
end = time.time()
print end-start

IndexError: single positional indexer is out-of-bounds

In [266]:
type(data.iloc[i,1].date()) , type(date)

(datetime.date, datetime.date)

In [276]:
data[data.GRPNUM==10018]

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
290,10018,2015-01-31,ACTIVE,1389.0,01-10-2011,150,40.016427,39,3.0,3.0,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,290,12
291,10018,2015-02-28,ACTIVE,1389.0,01-10-2011,150,40.936345,40,3.0,3.0,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,291,12
292,10018,2015-03-31,ACTIVE,1389.0,01-10-2011,150,41.954825,41,3.0,3.0,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,292,12
293,10018,2015-04-30,ACTIVE,1389.0,01-10-2011,150,42.940452,42,3.0,3.0,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,293,12
294,10018,2015-05-31,ACTIVE,1389.0,01-10-2011,200,43.958932,43,3.0,3.0,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,294,12
295,10018,2015-06-30,ACTIVE,1389.0,01-10-2011,200,44.944559,44,3.0,3.0,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,295,12
296,10018,2015-07-31,ACTIVE,1389.0,01-10-2011,200,46.089224,45,3.0,3.0,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,296,3
297,10018,2015-08-31,ACTIVE,1389.0,01-10-2011,200,46.981520,46,3.0,3.0,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,297,2
298,10018,2015-09-30,ACTIVE,1389.0,01-10-2011,200,47.967146,47,NaN,NaN,...,25-08-2014,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,298,1
299,10018,2015-10-31,LAPSED,1389.0,01-10-2011,625,48.985626,48,NaN,NaN,...,25-08-2015,No,Lapsed,Field Force,Never Enrolled,NaN,Non-MGA,No,299,0

In [275]:
lapsed

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y,freq
74,10006,2016-11-30,LAPSED,8211.0,01-11-2011,3500,60.977413,60,NaN,NaN,...,No,NaN,Broker,In Force,NaN,Non-MGA,No,74,0,1
211,10014,2015-04-30,LAPSED,8062.0,01-10-2011,115,42.940452,42,2.0,2.0,...,No,NaN,Field Force,Terminated,NaN,Non-MGA,No,211,0,1
299,10018,2015-10-31,LAPSED,1389.0,01-10-2011,625,48.985626,48,NaN,NaN,...,No,Lapsed,Field Force,Never Enrolled,NaN,Non-MGA,No,299,0,1
745,10042,2015-04-30,LAPSED,8211.0,01-10-2011,400,42.940452,42,NaN,NaN,...,No,NaN,Broker,Terminated,NaN,Non-MGA,No,745,0,1
763,10043,2016-06-30,LAPSED,8082.0,01-11-2011,6000,54.965100,55,25.0,24.0,...,Yes,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,763,0,1
780,10044,2016-05-31,LAPSED,3999.0,01-10-2011,201,55.983573,55,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,780,0,1
809,10046,2015-03-31,LAPSED,5812.0,01-10-2011,118,41.954825,41,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,809,0,1
981,10053,2016-04-30,LAPSED,3089.0,01-10-2011,400,54.965092,54,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,981,0,2
1196,10061,2016-12-31,LAPSED,9199.0,01-10-2011,2000,63.014374,62,1.0,0.0,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,Yes,1196,0,1
1235,10063,2016-01-31,LAPSED,9199.0,01-10-2011,108,52.008214,51,9.0,9.0,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,1235,0,1
1262,10066,2015-01-31,LAPSED,5599.0,01-11-2011,200,38.997947,38,NaN,NaN,...,No,NaN,Field Force,Never Enrolled,NaN,Non-MGA,No,1262,0,1
1310,10069,2016-10-31,LAPSED,5812.0,01-10-2011,420,61.010267,60,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,1310,0,1
1375,10072,2016-01-31,LAPSED,9199.0,01-10-2011,180,52.008214,51,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,1375,0,1
1413,10074,2015-12-31,LAPSED,8211.0,01-10-2011,141,50.989733,50,2.0,2.0,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,1413,0,1
1648,10087,2015-01-31,LAPSED,8059.0,01-10-2011,110,40.016427,39,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,1648,0,1
1705,10091,2015-05-31,LAPSED,8741.0,01-11-2011,150,42.940452,42,34.0,29.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,1705,0,1
1980,10105,2016-03-31,LAPSED,8322.0,01-10-2011,350,53.979466,53,NaN,NaN,...,No,NaN,Field Force,Terminated,NaN,Non-MGA,No,1980,0,1
2012,10107,2015-06-30,LAPSED,8011.0,01-10-2011,500,44.944559,44,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,2012,0,1
2141,10115,2017-01-31,LAPSED,5812.0,01-11-2011,390,63.014374,62,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,2141,0,1
2175,10119,2015-08-31,LAPSED,8299.0,01-09-2011,180,47.967146,47,NaN,NaN,...,NaN,NaN,Field Force,Past Enrollment,NaN,Non-MGA,No,2175,0,1
2201,10120,2015-12-31,LAPSED,8211.0,01-10-2011,680,50.989733,50,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,2201,0,1
2213,10122,2015-12-31,LAPSED,8299.0,01-10-2011,385,50.989733,50,4.0,3.0,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,2213,0,1
2314,10130,2016-11-30,LAPSED,8211.0,01-10-2011,325,61.995893,61,NaN,NaN,...,No,NaN,Broker,Terminated,NaN,Non-MGA,No,2314,0,1
2390,10135,2016-12-31,LAPSED,9199.0,01-10-2011,250,63.014374,62,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,2390,0,1
2401,10136,2015-11-30,LAPSED,4151.0,01-10-2011,150,49.971253,49,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,2401,0,1
2428,10139,2015-01-31,LAPSED,3441.0,01-11-2011,110,38.997947,38,3.0,3.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,2428,0,1
2490,10142,2015-10-31,LAPSED,5421.0,01-12-2011,100,46.981520,46,2.0,2.0,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,2490,0,1
2555,10145,2016-01-31,LAPSED,8211.0,01-11-2011,260,50.989733,50,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,2555,0,1
2595,10147,2016-02-29,LAPSED,5013.0,01-11-2011,100,51.942505,51,10.0,10.0,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,2595,0,1
2925,10167,2016-06-30,LAPSED,8059.0,01-11-2011,140,54.965100,55,34.0,33.0,...,No,NaN,Field Force,Duplicate,N,Non-MGA,Yes,2925,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180008,9802,2015-03-31,LAPSED,6062.0,01-04-2011,220,47.967146,47,1.0,1.0,...,No,NaN,Field Force,Past Enrollment,NaN,Non-MGA,Yes,180008,0,1
180052,9804,2016-10-31,LAPSED,3999.0,01-04-2011,125,67.022587,66,10.0,10.0,...,No,Terminated,Field Force,Terminated,N,Non-MGA,Yes,180052,0,1
180355,9820,2016-05-31,LAPSED,7334.0,01-05-2011,170,61.010267,60,NaN,NaN,...,No,In Force,Field Force,In Force,NaN,Non-MGA,No,180355,0,1
180553,9832,2015-08-31,LAPSED,7349.0,01-04-2011,153,52.993840,52,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,180553,0,1
180673,9839,2016-04-30,LAPSED,3999.0,01-05-2011,150,59.991786,59,NaN,NaN,...,No,NaN,Broker,In Force,NaN,Non-MGA,No,180673,0,1
180806,9847,2015-03-31,LAPSED,8059.0,01-05-2011,75,46.981520,46,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,180806,0,1
180849,9852,2016-05-31,LAPSED,8999.0,01-06-2011,105,59.991786,59,NaN,NaN,...,No,Cancelled,Field Force,Did Not Meet Participation,NaN,Non-MGA,No,180849,0,1
180944,9856,2016-05-31,LAPSED,4731.0,01-05-2011,100,61.010267,60,NaN,NaN,...,No,NaN,Field Force,In Force,NaN,Non-MGA,No,180944,0,1
180953,9857,2015-09-30,LAPSED,7011.0,01-05-2011,130,52.993840,52,10.0,10.0,...,No,NaN,Field Force,In Force,NaN,Non-MGA,Yes,180953,0,1
180984,9860,2015-05-31,LAPSED,4119.0,01-05-2011,246,48.985626,48,NaN,NaN,...,No,NaN,Broker,Terminated,NaN,Non-MGA,No,180984,0,1
180986,9861,2015-02-28,LAPSED,4213.0,01-05-2011,120,45.963039,45,NaN,NaN,...,No,NaN,Field Force,Terminated,NaN,Non-MGA,No,180986,0,1
181381,9891,2015-05-31,LAPSED,5599.0,01-05-2011,200,48.985626,48,NaN,NaN,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,181381,0,1
181527,9900,2016-04-30,LAPSED,5014.0,01-06-2011,101,58.973306,58,NaN,NaN,...,No,NaN,Broker,Cancelled by Group,NaN,Non-MGA,No,181527,0,2
181675,9911,2016-04-30,LAPSED,9421.0,01-05-2011,250,59.991786,59,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,181675,0,1
181679,9913,2015-04-30,LAPSED,8999.0,01-06-2011,120,46.948665,46,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,181679,0,1
181694,9915,2016-03-31,LAPSED,8351.0,01-05-2011,218,59.006160,58,7.0,5.0,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,Yes,181694,0,1
181843,9924,2016-07-31,LAPSED,8059.0,01-05-2011,294,63.014374,62,NaN,NaN,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,No,181843,0,1
182087,9938,2015-10-31,LAPSED,191.0,01-05-2011,300,54.012320,53,NaN,NaN,...,No,Cancelled,Broker,Cancelled by Group,NaN,Non-MGA,No,182087,0,1
182188,9945,2016-11-30,LAPSED,8062.0,01-05-2011,136,67.022587,66,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,182188,0,1
182382,9954,2015-12-31,LAPSED,3399.0,01-06-2011,100,54.997947,54,NaN,NaN,...,No,Lapse-Pending,Broker,Cancelled by Group,NaN,Non-MGA,No,182382,0,1
182391,9955,2015-09-30,LAPSED,5812.0,01-06-2011,180,51.975359,51,NaN,NaN,...,No,Lapse-Pending,Field Force,Cancelled by Group,NaN,Non-MGA,No,182391,0,1
182419,9961,2015-02-28,LAPSED,8399.0,01-05-2011,300,45.963039,45,NaN,NaN,...,NaN,NaN,Field Force,Terminated,NaN,Non-MGA,No,182419,0,1
182432,9963,2016-01-31,LAPSED,7011.0,01-05-2011,120,57.034908,56,NaN,NaN,...,No,Lapsed,Field Force,Never Enrolled,NaN,Non-MGA,No,182432,0,1
182545,9969,2015-09-30,LAPSED,9999.0,01-05-2011,100,52.993840,52,NaN,NaN,...,Yes,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,182545,0,1
182573,9972,2015-02-28,LAPSED,7349.0,01-05-2011,130,45.963039,45,3.0,0.0,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,182573,0,1
182710,9979,2015-07-31,LAPSED,8051.0,01-05-2011,102,51.129719,50,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,182710,0,1
182714,9980,2015-04-30,LAPSED,8059.0,01-05-2011,102,47.967146,47,NaN,NaN,...,No,NaN,Field Force,Cancelled by Group,NaN,Non-MGA,No,182714,0,1
182887,9991,2016-05-31,LAPSED,5812.0,01-06-2011,500,59.991786,59,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,Y,Non-MGA,No,182887,0,1
182893,9992,2015-06-30,LAPSED,8062.0,01-06-2011,400,48.952772,48,NaN,NaN,...,No,Cancelled,Field Force,Cancelled by Group,NaN,Non-MGA,No,182893,0,1
183018,A2,2016-09-30,LAPSED,NaN,01-03-2010,200,79.014374,78,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183018,0,1

In [278]:
len(data)

183019

In [292]:
data[data.GRPNUM=='A2']

,GRPNUM,VALUATION,STATUS,SIC_Code,Effective_Date,EE_Count,Tenure_Months,Tenure_Months1,Apps_Recd,Apps_Proc,...,Enrollment_End_Date,Exception_Report,Genelco_Group_Status,Market_Segment,Work_Status,Platform_Preferred,MGA_Flag,Aflac_Apps,sno,y
182998,A2,2015-01-31,ACTIVE,NaN,01-03-2010,200,59.039014,58,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182998,12
182999,A2,2015-02-28,ACTIVE,NaN,01-03-2010,200,59.958932,59,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,182999,12
183000,A2,2015-03-31,ACTIVE,NaN,01-03-2010,200,60.977413,60,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183000,12
183001,A2,2015-04-30,ACTIVE,NaN,01-03-2010,200,61.963039,61,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183001,12
183002,A2,2015-05-31,ACTIVE,NaN,01-03-2010,200,62.981520,62,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183002,12
183003,A2,2015-06-30,ACTIVE,NaN,01-03-2010,200,63.967146,63,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183003,12
183004,A2,2015-07-31,ACTIVE,NaN,01-03-2010,200,65.164036,64,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183004,12
183005,A2,2015-08-31,ACTIVE,NaN,01-03-2010,200,66.004107,65,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183005,12
183006,A2,2015-09-30,ACTIVE,NaN,01-03-2010,200,66.989733,66,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183006,12
183007,A2,2015-10-31,ACTIVE,NaN,01-03-2010,200,68.008214,67,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183007,12
183008,A2,2015-11-30,ACTIVE,NaN,01-03-2010,200,68.993840,68,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183008,12
183009,A2,2015-12-31,ACTIVE,NaN,01-03-2010,200,70.012320,69,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183009,12
183010,A2,2016-01-31,ACTIVE,NaN,01-03-2010,200,71.030801,70,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183010,12
183011,A2,2016-02-29,ACTIVE,NaN,01-03-2010,200,71.983573,71,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183011,12
183012,A2,2016-03-31,ACTIVE,NaN,01-03-2010,200,73.002053,72,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183012,12
183013,A2,2016-04-30,ACTIVE,NaN,01-03-2010,200,73.987680,73,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183013,12
183014,A2,2016-05-31,ACTIVE,NaN,01-03-2010,200,75.006160,74,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183014,12
183015,A2,2016-06-30,Active,NaN,01-03-2010,200,75.006200,75,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183015,3
183016,A2,2016-07-31,ACTIVE,NaN,01-03-2010,200,77.010267,76,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183016,0
183017,A2,2016-08-31,ACTIVE,NaN,01-03-2010,200,78.028747,77,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183017,0
183018,A2,2016-09-30,LAPSED,NaN,01-03-2010,200,79.014374,78,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Non-MGA,No,183018,0

In [294]:
data.to_csv("modelling.csv")